/-
  Crandall–Pomerance, Algorithm 4.3.4 (finite field primality test) —
  the mathematics: existence of witnesses for a prime `n`, and
  soundness of the "prime" verdict.

  The book's discussion before the algorithm answers "if `n` is
  prime, do `f, g` as in Theorem 4.3.3 exist?":

  * Condition (1) for any irreducible `f` and any `g` not a multiple
    of `f` is Lagrange's theorem in `K* = (Z_n[x]/(f))*`
    (`cond1_of_prime`).
  * Condition (3) holds for EVERY `g` (the book asks `f ∤ g`, but no
    hypothesis on `g` is needed): the Galois group of `K` is
    generated by the Frobenius map `α ↦ α^n`, which permutes
    `g, g^n, …, g^(n^(I−1))` cyclically — `Frobenius^I` is the
    identity on all of `K` — so the elementary symmetric functions
    are Frobenius-fixed and lie in the prime field
    (`cond3_of_prime`, via `mem_range_algebraMap_of_pow_card` from
    Theorem 4.2.4).
  * Condition (2) is satisfiable: `K*` is cyclic, and the
    degree-`< I` representative of any cyclic generator satisfies
    (1) and (2) for every prime `q ∣ n^I − 1`
    (`exists_lenstra_witness`).  (The book's step 2 says to choose
    `g` MONIC of degree `< I`, but its own probabilistic analysis
    correctly says "nonzero of degree less than `I`" — monic is a
    slip: at `I = 1` the only monic choice is `g = 1`, which
    satisfies (2) only vacuously.)

  Soundness of the algorithm's "prime" verdict
  (`prime_of_lenstra_conditions`): if the run has verified (1), (2),
  (3) — which is exactly what steps 2 and 3 check — and the divisor
  search of step 4 finds no proper factor among `n^j mod F` for
  `1 ≤ j < I`, then `n` is prime, provided `F ≥ √n`.  Indeed a
  composite `n` has a prime factor `p ≤ √n ≤ F`, and Theorem 4.3.3
  puts `p ≡ n^j (mod F)` for some `j < I`: `j = 0` forces the
  absurd `F ∣ p − 1` with `0 < p − 1 < F`; `p = F` forces
  `F ∣ gcd(n^j, n^I − 1) = 1`; and otherwise `p = n^j mod F` is a
  proper factor that step 4 would have found.  The "composite"
  verdicts are sound by `gcdOrFactor_factor` (steps 1 and 2 gcd
  failures), the contrapositive of `cond1_of_prime` (step 2 Fermat
  failure), and the contrapositive of `cond3_of_prime` (step 3).
-/
import Azurite.CrandallPomerance.Chapter4.Theorem_4_3_3
import Azurite.CrandallPomerance.Chapter4.Theorem_4_2_4
import Mathlib.FieldTheory.Finite.GaloisField
import Mathlib.FieldTheory.PrimitiveElement

namespace Azurite

namespace CP

open Polynomial

/-! ### Witnesses exist when `n` is prime -/

/-- **Condition (1) holds for a prime modulus**: if `n` is prime, `f`
is irreducible, and `g` is not a multiple of `f`, then
`f ∣ g^(n^(deg f)−1) − 1` — Lagrange's theorem in the multiplicative
group of `K = Z_n[x]/(f)`. -/
theorem cond1_of_prime {n I : ℕ} [Fact n.Prime] {f g : Polynomial (ZMod n)}
    (hirr : Irreducible f) (hdeg : f.natDegree = I) (hg : ¬f ∣ g) :
    f ∣ g ^ (n ^ I - 1) - 1 := by
  have : Fact (Irreducible f) := ⟨hirr⟩
  have : Module.Finite (ZMod n) (AdjoinRoot f) :=
    (AdjoinRoot.powerBasis hirr.ne_zero).finite
  have : Finite (AdjoinRoot f) := Module.finite_of_finite (ZMod n)
  have : Fintype (AdjoinRoot f) := Fintype.ofFinite _
  have hcard : Fintype.card (AdjoinRoot f) = n ^ I := by
    rw [Module.card_eq_pow_finrank (K := ZMod n) (V := AdjoinRoot f),
      (AdjoinRoot.powerBasis hirr.ne_zero).finrank,
      AdjoinRoot.powerBasis_dim, ZMod.card, hdeg]
  have hne : AdjoinRoot.mk f g ≠ 0 := by
    rw [Ne, AdjoinRoot.mk_eq_zero]
    exact hg
  have h1 := FiniteField.pow_card_sub_one_eq_one (AdjoinRoot.mk f g) hne
  rw [hcard] at h1
  rw [← AdjoinRoot.mk_eq_zero, map_sub, map_pow, map_one, h1, sub_self]

/-- The index rotation `j ↦ (j+1) mod I` permutes `range I`. -/
private theorem range_map_succ_mod {I : ℕ} (hI : 0 < I) :
    (Multiset.range I).map (fun j => (j + 1) % I) = Multiset.range I := by
  have hnodup : ((Multiset.range I).map (fun j => (j + 1) % I)).Nodup := by
    refine (Multiset.nodup_range I).map_on ?_
    intro a ha b hb hab
    rw [Multiset.mem_range] at ha hb
    have ha' : a + 1 = I ∨ a + 1 < I := by omega
    have hb' : b + 1 = I ∨ b + 1 < I := by omega
    rcases ha' with haI | haI <;> rcases hb' with hbI | hbI
    · omega
    · rw [haI, Nat.mod_self, Nat.mod_eq_of_lt hbI] at hab
      omega
    · rw [hbI, Nat.mod_self, Nat.mod_eq_of_lt haI] at hab
      omega
    · rw [Nat.mod_eq_of_lt haI, Nat.mod_eq_of_lt hbI] at hab
      omega
  rw [(hnodup.ext (Multiset.nodup_range I))]
  intro a
  rw [Multiset.mem_map]
  constructor
  · rintro ⟨j, hj, rfl⟩
    rw [Multiset.mem_range] at hj ⊢
    exact Nat.mod_lt _ hI
  · intro ha
    rw [Multiset.mem_range] at ha
    rcases Nat.eq_zero_or_pos a with rfl | ha0
    · exact ⟨I - 1, Multiset.mem_range.mpr (by omega), by
        rw [show I - 1 + 1 = I by omega, Nat.mod_self]⟩
    · exact ⟨a - 1, Multiset.mem_range.mpr (by omega), by
        rw [show a - 1 + 1 = a by omega, Nat.mod_eq_of_lt ha]⟩

/-- **Condition (3) holds for a prime modulus — for every `g`**: if
`n` is prime and `f` is irreducible of degree `I`, each elementary
symmetric polynomial in `g, g^n, …, g^(n^(I−1))` is congruent mod `f`
to a constant.  The Frobenius map permutes the powers cyclically (it
has order dividing `I` on `K`), so the symmetric functions are
Frobenius-fixed, hence in the prime field. -/
theorem cond3_of_prime {n I : ℕ} [Fact n.Prime] (hI : 0 < I)
    {f : Polynomial (ZMod n)} (hirr : Irreducible f)
    (hdeg : f.natDegree = I) (g : Polynomial (ZMod n)) :
    ∀ k : ℕ, 1 ≤ k → k ≤ I → ∃ c : ZMod n,
      f ∣ ((Multiset.range I).map fun j => g ^ n ^ j).esymm k - C c := by
  intro k _ _
  have : Fact (Irreducible f) := ⟨hirr⟩
  have : Module.Finite (ZMod n) (AdjoinRoot f) :=
    (AdjoinRoot.powerBasis hirr.ne_zero).finite
  have : Finite (AdjoinRoot f) := Module.finite_of_finite (ZMod n)
  have : Fintype (AdjoinRoot f) := Fintype.ofFinite _
  have : DecidableEq (AdjoinRoot f) := Classical.decEq _
  have : CharP (AdjoinRoot f) n :=
    charP_of_injective_algebraMap
      (algebraMap (ZMod n) (AdjoinRoot f)).injective n
  have hcard : Fintype.card (AdjoinRoot f) = n ^ I := by
    rw [Module.card_eq_pow_finrank (K := ZMod n) (V := AdjoinRoot f),
      (AdjoinRoot.powerBasis hirr.ne_zero).finrank,
      AdjoinRoot.powerBasis_dim, ZMod.card, hdeg]
  -- the conjugate multiset is Frobenius-invariant
  set S : Multiset (AdjoinRoot f) :=
    (Multiset.range I).map (fun j => AdjoinRoot.mk f g ^ n ^ j) with hS
  have hSfrob : S.map (frobenius (AdjoinRoot f) n) = S := by
    have hstep : ∀ j ∈ Multiset.range I,
        frobenius (AdjoinRoot f) n (AdjoinRoot.mk f g ^ n ^ j)
          = AdjoinRoot.mk f g ^ n ^ ((j + 1) % I) := by
      intro j hj
      rw [Multiset.mem_range] at hj
      rw [frobenius_def, ← pow_mul, ← pow_succ]
      have hj' : j + 1 = I ∨ j + 1 < I := by omega
      rcases hj' with heq | hlt
      · rw [heq, Nat.mod_self, pow_zero, pow_one, ← hcard]
        exact FiniteField.pow_card _
      · rw [Nat.mod_eq_of_lt hlt]
    have hcalc1 : S.map (frobenius (AdjoinRoot f) n)
        = (Multiset.range I).map
            (fun j => AdjoinRoot.mk f g ^ n ^ ((j + 1) % I)) := by
      rw [hS, Multiset.map_map]
      exact Multiset.map_congr rfl hstep
    have hcalc2 : (Multiset.range I).map
        (fun j => AdjoinRoot.mk f g ^ n ^ ((j + 1) % I))
        = ((Multiset.range I).map (fun j => (j + 1) % I)).map
            (fun j => AdjoinRoot.mk f g ^ n ^ j) := by
      rw [Multiset.map_map]
      rfl
    rw [hcalc1, hcalc2, range_map_succ_mod hI, hS]
  -- so its symmetric functions are Frobenius-fixed, hence constants
  have hfix : S.esymm k ^ n = S.esymm k := by
    have := esymm_map (frobenius (AdjoinRoot f) n) S k
    rw [hSfrob] at this
    rw [← frobenius_def (R := AdjoinRoot f) (p := n)]
    exact this.symm
  obtain ⟨c, hc⟩ := mem_range_algebraMap_of_pow_card (p := n) hfix
  refine ⟨c, ?_⟩
  rw [← AdjoinRoot.mk_eq_zero, map_sub, sub_eq_zero]
  have hmk : AdjoinRoot.mk f
      (((Multiset.range I).map fun j => g ^ n ^ j).esymm k) = S.esymm k := by
    rw [← esymm_map (AdjoinRoot.mk f), Multiset.map_map, hS]
    congr 1
  rw [hmk, ← hc, AdjoinRoot.algebraMap_eq]
  rfl

/-- **A full witness exists when `n` is prime**: for irreducible monic
`f` of degree `I`, the degree-`< I` representative of a cyclic
generator of `K*` satisfies condition (1) and condition (2) for EVERY
prime `q ∣ n^I − 1` (condition (3) holds for every `g` by
`cond3_of_prime`). -/
theorem exists_lenstra_witness {n I : ℕ} [Fact n.Prime] (hI : 0 < I)
    {f : Polynomial (ZMod n)} (hf : f.Monic) (hirr : Irreducible f)
    (hdeg : f.natDegree = I) :
    ∃ g : Polynomial (ZMod n), g.natDegree < I ∧
      f ∣ g ^ (n ^ I - 1) - 1 ∧
      ∀ q : ℕ, q.Prime → q ∣ n ^ I - 1 →
        IsCoprime (g ^ ((n ^ I - 1) / q) - 1) f := by
  have : Fact (Irreducible f) := ⟨hirr⟩
  have : Module.Finite (ZMod n) (AdjoinRoot f) :=
    (AdjoinRoot.powerBasis hirr.ne_zero).finite
  have : Finite (AdjoinRoot f) := Module.finite_of_finite (ZMod n)
  have : Fintype (AdjoinRoot f) := Fintype.ofFinite _
  have hcard : Fintype.card (AdjoinRoot f) = n ^ I := by
    rw [Module.card_eq_pow_finrank (K := ZMod n) (V := AdjoinRoot f),
      (AdjoinRoot.powerBasis hirr.ne_zero).finrank,
      AdjoinRoot.powerBasis_dim, ZMod.card, hdeg]
  have hN0 : 0 < n ^ I - 1 := by
    have h2 : 2 ≤ n := (Fact.out (p := n.Prime)).two_le
    have h2n : 2 ≤ n ^ I := le_trans h2 (Nat.le_self_pow hI.ne' n)
    omega
  -- a cyclic generator of `K*` and its reduced representative
  obtain ⟨ζ, hζ⟩ := IsCyclic.exists_generator (α := (AdjoinRoot f)ˣ)
  have hordζ : orderOf ζ = n ^ I - 1 := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hζ, Nat.card_eq_fintype_card,
      Fintype.card_units, hcard]
  obtain ⟨g₀, hg₀⟩ := AdjoinRoot.mk_surjective (ζ : AdjoinRoot f)
  refine ⟨g₀ %ₘ f, ?_, ?_, ?_⟩
  case refine_1 =>
    by_cases h0 : g₀ %ₘ f = 0
    · rw [h0, natDegree_zero]
      exact hI
    · have hdlt : (g₀ %ₘ f).degree < f.degree := degree_modByMonic_lt g₀ hf
      have := natDegree_lt_natDegree h0 hdlt
      omega
  all_goals
    have hmkg : AdjoinRoot.mk f (g₀ %ₘ f) = (ζ : AdjoinRoot f) := by
      rw [← hg₀]
      refine AdjoinRoot.mk_eq_mk.mpr ⟨-(g₀ /ₘ f), ?_⟩
      have hrec := modByMonic_add_div g₀ f
      linear_combination hrec
  case refine_2 =>
    rw [← AdjoinRoot.mk_eq_zero, map_sub, map_pow, map_one, hmkg,
      ← Units.val_pow_eq_pow_val, ← hordζ, pow_orderOf_eq_one,
      Units.val_one, sub_self]
  case refine_3 =>
    intro q hq hqN
    have hnotdvd : ¬f ∣ (g₀ %ₘ f) ^ ((n ^ I - 1) / q) - 1 := by
      intro hdvd
      have h0 : AdjoinRoot.mk f ((g₀ %ₘ f) ^ ((n ^ I - 1) / q) - 1) = 0 :=
        AdjoinRoot.mk_eq_zero.mpr hdvd
      rw [map_sub, map_pow, map_one, hmkg, sub_eq_zero] at h0
      have h0' : ζ ^ ((n ^ I - 1) / q) = 1 := Units.ext (by
        rw [Units.val_pow_eq_pow_val, Units.val_one]
        exact h0)
      have hdvdord : orderOf ζ ∣ (n ^ I - 1) / q :=
        orderOf_dvd_of_pow_eq_one h0'
      rw [hordζ] at hdvdord
      have hlt : (n ^ I - 1) / q < n ^ I - 1 :=
        Nat.div_lt_self hN0 hq.one_lt
      have hpos : 0 < (n ^ I - 1) / q :=
        Nat.div_pos (Nat.le_of_dvd hN0 hqN) hq.pos
      have := Nat.le_of_dvd hpos hdvdord
      omega
    exact ((hirr.coprime_iff_not_dvd).mpr hnotdvd).symm

/-! ### Soundness of the "prime" verdict -/

/-- **Algorithm 4.3.4's "prime" verdict is sound**: if `F ≥ √n` (as
`n ≤ F²`), the verified conditions (1), (2), (3) hold, and the step-4
divisor search finds no proper factor of `n` among the residues
`n^j mod F` for `1 ≤ j < I`, then `n` is prime. -/
theorem prime_of_lenstra_conditions {n I F : ℕ} (hn : 1 < n) (hI : 0 < I)
    (hF : 0 < F) (hFN : F ∣ n ^ I - 1) (hF2 : n ≤ F ^ 2)
    {f g : Polynomial (ZMod n)} (hf : f.Monic) (hfdeg : 0 < f.natDegree)
    (h1 : f ∣ g ^ (n ^ I - 1) - 1)
    (h2 : ∀ q : ℕ, q.Prime → q ∣ F →
      IsCoprime (g ^ ((n ^ I - 1) / q) - 1) f)
    (h3 : ∀ k : ℕ, 1 ≤ k → k ≤ I → ∃ c : ZMod n,
      f ∣ ((Multiset.range I).map fun j => g ^ n ^ j).esymm k - C c)
    (h4 : ∀ j : ℕ, 0 < j → j < I →
      ¬(n ^ j % F ∣ n ∧ 1 < n ^ j % F ∧ n ^ j % F < n)) :
    n.Prime := by
  by_contra hcomp
  -- a composite `n` has a prime factor `p ≤ √n ≤ F`
  obtain ⟨p, hpdef⟩ : ∃ p, p = n.minFac := ⟨_, rfl⟩
  have hp : p.Prime := hpdef ▸ Nat.minFac_prime (by omega)
  have hpn : p ∣ n := hpdef ▸ Nat.minFac_dvd n
  have hpsq : p * p ≤ n := by
    have := Nat.minFac_sq_le_self (by omega) hcomp
    rw [← hpdef] at this
    calc p * p = p ^ 2 := (sq p).symm
      _ ≤ n := this
  have hpF : p ≤ F := by
    by_contra hgt
    push Not at hgt
    have h1 : F * F < p * p :=
      Nat.mul_lt_mul_of_lt_of_le hgt (le_of_lt hgt) (by omega)
    have h2 : F ^ 2 = F * F := sq F
    omega
  have hplt : p < n := by
    have h2p : 2 * p ≤ p * p := Nat.mul_le_mul_right p hp.two_le
    omega
  have hF2' : 2 ≤ F := le_trans hp.two_le hpF
  -- Theorem 4.3.3 confines `p` to the classes `n^j mod F`
  obtain ⟨j, hjI, hmod⟩ :=
    theorem_4_3_3 hn hI hF hFN hf hfdeg h1 h2 h3 hp hpn
  rcases Nat.eq_zero_or_pos j with rfl | hj0
  · -- `j = 0`: `F ∣ p − 1` with `0 < p − 1 < F` is absurd
    rw [pow_zero] at hmod
    have hdvd : F ∣ p - 1 := (Nat.modEq_iff_dvd' hp.one_lt.le).mp hmod.symm
    have := Nat.le_of_dvd (by have := hp.two_le; omega) hdvd
    omega
  · -- `j ≥ 1`: `p` equals the residue `n^j mod F`, a proper factor
    have hmodeq : p % F = n ^ j % F := hmod
    rcases Nat.eq_or_lt_of_le hpF with rfl | hpltF
    · -- `p = F` forces `F ∣ gcd(n^j, n^I − 1) = 1`
      rw [Nat.mod_self] at hmodeq
      have hdvdj : p ∣ n ^ j := Nat.dvd_of_mod_eq_zero hmodeq.symm
      have hcop : Nat.Coprime n (n ^ I - 1) := by
        have hdn : Nat.gcd n (n ^ I - 1) ∣ n ^ I :=
          dvd_pow (Nat.gcd_dvd_left _ _) hI.ne'
        have hdN : Nat.gcd n (n ^ I - 1) ∣ n ^ I - 1 :=
          Nat.gcd_dvd_right _ _
        have hsub := Nat.dvd_sub hdn hdN
        rw [show n ^ I - (n ^ I - 1) = 1 by
          have h2n : 2 ≤ n ^ I := le_trans hn (Nat.le_self_pow hI.ne' n)
          omega] at hsub
        exact Nat.dvd_one.mp hsub
      have hgcd := Nat.dvd_gcd hdvdj hFN
      rw [Nat.Coprime.pow_left j hcop] at hgcd
      have := Nat.dvd_one.mp hgcd
      have := hp.two_le
      omega
    · -- `p < F`: the residue is `p` itself
      rw [Nat.mod_eq_of_lt hpltF] at hmodeq
      exact h4 j hj0 hjI ⟨hmodeq ▸ hpn, hmodeq ▸ hp.one_lt, hmodeq ▸ hplt⟩

/-- **Irreducible polynomials of every degree exist over `Z_p`** (the
book's "Are there irreducible polynomials in `Z_n[x]` of degree `I`?
Yes."): the minimal polynomial of a primitive element of
`GF(p^I)`. -/
theorem exists_monic_irreducible_of_degree (p I : ℕ) [Fact p.Prime]
    (hI : 0 < I) :
    ∃ f : Polynomial (ZMod p), f.Monic ∧ Irreducible f
      ∧ f.natDegree = I := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element_of_finite_top
    (ZMod p) (GaloisField p I)
  have hint : IsIntegral (ZMod p) α := .of_finite _ _
  refine ⟨minpoly (ZMod p) α, minpoly.monic hint,
    minpoly.irreducible hint, ?_⟩
  rw [← IntermediateField.adjoin.finrank hint, hα,
    IntermediateField.finrank_top', GaloisField.finrank p hI.ne']

end CP

end Azurite

/-! ### A worked instance

The same degenerate `I = 1` data as for Theorem 4.3.3, now driven to a
primality PROOF through the divisor search: `n = 3`, `F = 2 ≥ √3`,
`f = x`, `g = 2` — the step-4 range `1 ≤ j < 1` is empty, so the
conditions alone prove `3` prime. -/

section Examples

open Polynomial Azurite.CP

example : Nat.Prime 3 := by
  refine prime_of_lenstra_conditions (n := 3) (I := 1) (F := 2)
    (by norm_num) one_pos (by norm_num) (by norm_num) (by norm_num)
    (f := (X : Polynomial (ZMod 3))) (g := C 2)
    monic_X
    (by
      have : Fact (1 < 3) := ⟨by norm_num⟩
      rw [natDegree_X]
      exact one_pos)
    ?_ ?_ ?_ ?_
  · -- (1): `x ∣ C 2 ^ 2 − 1 = C (4 − 1) = C 0`
    have h22 : (2 : ZMod 3) ^ 2 - 1 = 0 := by decide
    rw [show (3 : ℕ) ^ 1 - 1 = 2 by norm_num, ← C_pow, ← C_1, ← C_sub,
      h22, C_0]
    exact dvd_zero _
  · -- (2): the only prime divisor of `F = 2` is `2`, and `2^1 − 1 = 1`
    intro q hq hq2
    have hqle : q ≤ 2 := Nat.le_of_dvd (by norm_num) hq2
    have hq2' : 2 ≤ q := hq.two_le
    interval_cases q
    have h1 : (2 : ZMod 3) ^ 1 - 1 = 1 := by decide
    rw [show ((3 : ℕ) ^ 1 - 1) / 2 = 1 by norm_num, ← C_pow, ← C_1,
      ← C_sub, h1, C_1]
    exact isCoprime_one_left
  · -- (3): the symmetric function of the singleton `{g}` is `g` itself
    intro k hk1 hkI
    obtain rfl : k = 1 := by omega
    refine ⟨2, ?_⟩
    have hsingle : ((Multiset.range 1).map
        fun j => (C (2 : ZMod 3)) ^ 3 ^ j).esymm 1 = C 2 := by
      simp [Multiset.esymm, Multiset.powersetCard_one]
    rw [hsingle, sub_self]
    exact dvd_zero _
  · -- (4): the divisor-search range `1 ≤ j < 1` is empty
    intro j hj1 hj2
    omega

end Examples
