/-
Copyright © 2026 Mikhail Hogrefe

This file is part of Azurite.

Azurite is free software: you can redistribute it and/or modify it under the terms of the Apache
License, Version 2.0. See <https://www.apache.org/licenses/LICENSE-2.0>.
-/

/-
  The `ℤ[ζ_p, ζ_q]` model is FAITHFUL: for distinct primes `p, q`,
  the tower `CycPQ p q` of Definition 4.4.4 is an integral domain and
  its symbols `zetaP`, `zetaQ` are genuine primitive roots of unity —
  the facts that let the abstract Lemmas 4.4.1–4.4.3 (stated over any
  domain carrying the roots) be INSTANTIATED at the model.

  The route: embed the tower into the cyclotomic field
  `L = ℚ(ζ_pq)` by sending the symbols to `η^q` and `η^p` (`η` a
  primitive `pq`-th root), via a double `AdjoinRoot.lift`
  (`cycEmb`).  Injectivity is the heart: the images of the
  `ℤ`-basis monomials are `(η^q)^i (η^p)^k`, and these are
  `ℚ`-linearly independent because they form the product of the
  power basis of `ℚ(ζ_p)` over `ℚ` with a power basis of `L` over
  `ℚ(ζ_p)` generated by `η^p` — the latter exists because
  `ℚ(ζ_p)(ζ_q) = L` (Bézout: `η = (η^q)^a (η^p)^b` from
  `aq + bp = 1 + t·pq`) together with the degree count
  `φ(pq) = (p−1)(q−1)`.  A domain injecting into a field, with
  primitivity reflected along the injection, gives everything else.

  Consequences recorded here:
  * `isDomain_cycPQ`, `isPrimitiveRoot_zetaP/Q` — the instantiation
    facts for Lemmas 4.4.1–4.4.3;
  * `natCast_dvd_natCast_iff` — integers are faithful in the model:
    `(n : CycPQ) ∣ (m : CycPQ) ↔ n ∣ m`, converting Lemma 4.4.3's
    ring-form hypothesis into the book's `n ∤ m`.
-/
import Azurite.CrandallPomerance.Chapter4.Definition_4_4_4
import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots

namespace Azurite

namespace CP

open Polynomial Module IntermediateField

variable (p q : ℕ) [Fact p.Prime] [Fact q.Prime]

section Embedding

private theorem hp_pos : 0 < p := (Fact.out (p := p.Prime)).pos
private theorem hq_pos : 0 < q := (Fact.out (p := q.Prime)).pos

instance : NeZero (p * q) :=
  ⟨Nat.mul_ne_zero (hp_pos p).ne' (hq_pos q).ne'⟩

instance : NeZero ((p * q : ℕ) : ℚ) :=
  ⟨by exact_mod_cast Nat.mul_ne_zero (hp_pos p).ne' (hq_pos q).ne'⟩

instance : IsCyclotomicExtension {p * q} ℚ (CyclotomicField (p * q) ℚ) :=
  CyclotomicField.instIsCyclotomicExtensionSingletonNatSetOfCharZero
    (p * q) ℚ

/-- The ambient primitive `pq`-th root of unity. -/
noncomputable def eta : CyclotomicField (p * q) ℚ :=
  IsCyclotomicExtension.zeta (p * q) ℚ _

private theorem eta_spec : IsPrimitiveRoot (eta p q) (p * q) :=
  IsCyclotomicExtension.zeta_spec (p * q) ℚ (CyclotomicField (p * q) ℚ)

/-- `η^q` is a primitive `p`-th root of unity. -/
private theorem etaQ_pow_spec :
    IsPrimitiveRoot (eta p q ^ q) p := by
  have h := (eta_spec p q).pow_of_dvd (hq_pos q).ne' (dvd_mul_left q p)
  rwa [Nat.mul_div_cancel _ (hq_pos q)] at h

/-- `η^p` is a primitive `q`-th root of unity. -/
private theorem etaP_pow_spec :
    IsPrimitiveRoot (eta p q ^ p) q := by
  have h := (eta_spec p q).pow_of_dvd (hp_pos p).ne' (dvd_mul_right p q)
  rwa [Nat.mul_div_cancel_left _ (hp_pos p)] at h

private theorem eval₂_cyclotomic_int {R : Type _} [CommRing R] [IsDomain R]
    {m : ℕ} (hm : 0 < m) {ζ : R} (hζ : IsPrimitiveRoot ζ m) :
    (cyclotomic m ℤ).eval₂ (Int.castRingHom R) ζ = 0 := by
  rw [eval₂_eq_eval_map, map_cyclotomic]
  exact hζ.isRoot_cyclotomic hm

/-- The first leg: `ℤ[ζ_p] → L`, `ζ_p ↦ η^q`. -/
noncomputable def cycEmbP : CycP p →+* CyclotomicField (p * q) ℚ :=
  AdjoinRoot.lift (Int.castRingHom _) (eta p q ^ q)
    (eval₂_cyclotomic_int (hp_pos p) (etaQ_pow_spec p q))

/-- The embedding `ℤ[ζ_p, ζ_q] → ℚ(ζ_pq)`, `ζ_p ↦ η^q`,
`ζ_q ↦ η^p`. -/
noncomputable def cycEmb : CycPQ p q →+* CyclotomicField (p * q) ℚ :=
  AdjoinRoot.lift (cycEmbP p q) (eta p q ^ p) (by
    rw [show cyclotomic q (CycP p)
        = map (Int.castRingHom (CycP p)) (cyclotomic q ℤ) from
        (map_cyclotomic q (Int.castRingHom (CycP p))).symm,
      eval₂_map,
      Subsingleton.elim ((cycEmbP p q).comp (Int.castRingHom (CycP p)))
        (Int.castRingHom _)]
    exact eval₂_cyclotomic_int (hq_pos q) (etaP_pow_spec p q))

@[simp] private theorem cycEmb_zetaP :
    cycEmb p q (zetaP p q) = eta p q ^ q := by
  rw [zetaP, cycEmb]
  rw [show (algebraMap (CycP p) (CycPQ p q)) (AdjoinRoot.root _)
      = AdjoinRoot.of _ (AdjoinRoot.root _) from rfl,
    AdjoinRoot.lift_of, cycEmbP, AdjoinRoot.lift_root]

@[simp] private theorem cycEmb_zetaQ :
    cycEmb p q (zetaQ p q) = eta p q ^ p := by
  rw [zetaQ, cycEmb, AdjoinRoot.lift_root]

end Embedding

section Independence

variable (hpq : p ≠ q)

/-- The base subfield `ℚ(ζ_p) = ℚ⟮η^q⟯` inside `L`. -/
noncomputable abbrev KP : IntermediateField ℚ (CyclotomicField (p * q) ℚ) :=
  ℚ⟮eta p q ^ q⟯

private theorem finrank_KP : finrank ℚ (KP p q) = p - 1 := by
  rw [IntermediateField.adjoin.finrank (IsIntegral.of_finite _ _),
    ← cyclotomic_eq_minpoly_rat (etaQ_pow_spec p q) (hp_pos p),
    natDegree_cyclotomic, Nat.totient_prime (Fact.out (p := p.Prime))]

include hpq in
private theorem finrank_L :
    finrank ℚ (CyclotomicField (p * q) ℚ) = (p - 1) * (q - 1) := by
  rw [IsCyclotomicExtension.finrank (CyclotomicField (p * q) ℚ)
      (cyclotomic.irreducible_rat (Nat.mul_pos (hp_pos p) (hq_pos q))),
    Nat.totient_mul ((Nat.coprime_primes (Fact.out (p := p.Prime))
      (Fact.out (p := q.Prime))).mpr hpq),
    Nat.totient_prime (Fact.out (p := p.Prime)),
    Nat.totient_prime (Fact.out (p := q.Prime))]

include hpq in
/-- Bézout in natural numbers: `aq + bp = 1 + t·pq` — so that
`η = (η^q)^a · (η^p)^b`, subalgebra-friendly (no inverses). -/
private theorem exists_nat_bezout :
    ∃ a b t : ℕ, a * q + b * p = 1 + t * (p * q) := by
  have hco : Nat.Coprime q p :=
    (Nat.coprime_primes (Fact.out (p := q.Prime))
      (Fact.out (p := p.Prime))).mpr (Ne.symm hpq)
  obtain ⟨a, -, ha⟩ := Nat.exists_mul_mod_eq_one_of_coprime hco
    (Fact.out (p := p.Prime)).one_lt
  -- `q·a = 1 + s·p`; take `b := s(q−1)`, `t := s`
  obtain ⟨s, hs⟩ : ∃ s, q * a = 1 + s * p := by
    refine ⟨q * a / p, ?_⟩
    have h1 := Nat.div_add_mod (q * a) p
    have h2 : p * (q * a / p) = q * a / p * p := Nat.mul_comm _ _
    omega
  obtain ⟨q', rfl⟩ : ∃ q', q = q' + 1 :=
    ⟨q - 1, by have := (Fact.out (p := q.Prime)).two_le; omega⟩
  refine ⟨a, s * q', s, ?_⟩
  have hexp : s * q' + s = s * (q' + 1) := by ring
  nlinarith [hs]

set_option maxHeartbeats 800000 in
include hpq in
/-- `L` is generated over `ℚ(ζ_p)` by `η^p`. -/
private theorem adjoin_etaP_eq_top :
    Algebra.adjoin (KP p q) {eta p q ^ p} = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  -- `L = ℚ-adjoin η ⊆ K'-adjoin η ⊆ K'-adjoin (η^p)`
  have hη : eta p q ∈ Algebra.adjoin (KP p q) {eta p q ^ p} := by
    obtain ⟨a, b, t, habt⟩ := exists_nat_bezout p q hpq
    have hcalc : eta p q = (eta p q ^ q) ^ a * (eta p q ^ p) ^ b := by
      rw [← pow_mul, ← pow_mul, ← pow_add, Nat.mul_comm q a,
        Nat.mul_comm p b, habt, pow_add, pow_one, pow_mul',
        (eta_spec p q).pow_eq_one, one_pow, mul_one]
    have hζp'mem : (eta p q ^ q : CyclotomicField (p * q) ℚ)
        ∈ Algebra.adjoin (KP p q) {eta p q ^ p} := by
      have hrw : eta p q ^ q
          = algebraMap (KP p q) (CyclotomicField (p * q) ℚ)
            ⟨eta p q ^ q, IntermediateField.mem_adjoin_simple_self ℚ _⟩ :=
        rfl
      rw [hrw]
      exact Subalgebra.algebraMap_mem _ _
    have hmem : (eta p q ^ q) ^ a * (eta p q ^ p) ^ b
        ∈ Algebra.adjoin (KP p q) {eta p q ^ p} :=
      mul_mem (pow_mem hζp'mem a)
        (pow_mem (Algebra.self_mem_adjoin_singleton _ _) b)
    simpa only [← hcalc] using hmem
  have htop : Algebra.adjoin ℚ {eta p q} = ⊤ :=
    IsCyclotomicExtension.adjoin_primitive_root_eq_top (eta_spec p q)
  have hx : x ∈ Algebra.adjoin ℚ {eta p q} := htop ▸ Algebra.mem_top
  have hle : Algebra.adjoin ℚ {eta p q}
      ≤ (Algebra.adjoin (KP p q) {eta p q ^ p}).restrictScalars ℚ := by
    rw [Algebra.adjoin_le_iff]
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    exact hη
  exact hle hx

include hpq in
private theorem finrank_KP_L :
    finrank (KP p q) (CyclotomicField (p * q) ℚ) = q - 1 := by
  have hmul := Module.finrank_mul_finrank ℚ (KP p q)
    (CyclotomicField (p * q) ℚ)
  rw [finrank_KP, finrank_L p q hpq] at hmul
  have hp2 := (Fact.out (p := p.Prime)).two_le
  have hpos : 0 < finrank (KP p q) (CyclotomicField (p * q) ℚ) :=
    finrank_pos
  exact Nat.eq_of_mul_eq_mul_left (by omega) hmul

/-- The power basis of `L` over `ℚ(ζ_p)` generated by `η^p`. -/
private noncomputable def pbQ :
    PowerBasis (KP p q) (CyclotomicField (p * q) ℚ) :=
  (Algebra.adjoin.powerBasis (IsIntegral.of_finite _ (eta p q ^ p))).map
    ((Subalgebra.equivOfEq _ _ (adjoin_etaP_eq_top p q hpq)).trans
      Subalgebra.topEquiv)

private theorem pbQ_gen : (pbQ p q hpq).gen = eta p q ^ p := by
  rw [pbQ, PowerBasis.map_gen, Algebra.adjoin.powerBasis_gen]
  rfl

private theorem pbQ_dim : (pbQ p q hpq).dim = q - 1 := by
  have h := (pbQ p q hpq).finrank
  rw [finrank_KP_L p q hpq] at h
  omega

/-- The power basis of `ℚ(ζ_p)` over `ℚ`. -/
private noncomputable def pbP : PowerBasis ℚ (KP p q) :=
  IntermediateField.adjoin.powerBasis (IsIntegral.of_finite _ _)

private theorem pbP_dim : (pbP p q).dim = p - 1 := by
  rw [pbP, IntermediateField.adjoin.powerBasis_dim,
    ← cyclotomic_eq_minpoly_rat (etaQ_pow_spec p q) (hp_pos p),
    natDegree_cyclotomic, Nat.totient_prime (Fact.out (p := p.Prime))]

include hpq in
/-- **The core independence**: the monomials `(η^q)^i (η^p)^k` are
`ℤ`-linearly independent in `L`. -/
private theorem monomials_linearIndependent :
    LinearIndependent ℤ (fun ik : Fin (p - 1) × Fin (q - 1) =>
      (eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ)) := by
  -- the product of the two power bases is a `ℚ`-basis of `L`
  have hQ : LinearIndependent ℚ (fun ik : Fin (p - 1) × Fin (q - 1) =>
      (eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ)) := by
    have hb := (((pbP p q).basis.reindex (finCongr (pbP_dim p q))).smulTower
      ((pbQ p q hpq).basis.reindex
        (finCongr (pbQ_dim p q hpq)))).linearIndependent
    have hval : ∀ ik : Fin (p - 1) × Fin (q - 1),
        (((pbP p q).basis.reindex (finCongr (pbP_dim p q))).smulTower
          ((pbQ p q hpq).basis.reindex
            (finCongr (pbQ_dim p q hpq)))) ik
          = (eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ) := by
      rintro ⟨i, k⟩
      rw [Basis.smulTower_apply, Algebra.smul_def]
      congr 1
      · rw [Basis.reindex_apply, PowerBasis.basis_eq_pow, map_pow]
        congr 1
      · rw [Basis.reindex_apply, PowerBasis.basis_eq_pow, pbQ_gen]
        rfl
    rwa [show ⇑(((pbP p q).basis.reindex (finCongr (pbP_dim p q))).smulTower
      ((pbQ p q hpq).basis.reindex (finCongr (pbQ_dim p q hpq))))
      = fun ik : Fin (p - 1) × Fin (q - 1) =>
        (eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ)
      from funext hval] at hb
  exact hQ.restrict_scalars (by
    intro a b hab
    simpa using hab)

include hpq in
/-- **The embedding is injective** — the model is faithful. -/
theorem cycEmb_injective : Function.Injective (cycEmb p q) := by
  have hmap : ∀ ik : Fin (p - 1) × Fin (q - 1),
      cycEmb p q (cycBasis p q ik)
        = (eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ) := by
    rintro ⟨i, k⟩
    rw [cycBasis_apply, map_mul, map_pow, map_pow, cycEmb_zetaP,
      cycEmb_zetaQ]
  have hker : ∀ z : CycPQ p q, cycEmb p q z = 0 → z = 0 := by
    intro z hz
    have hexp : z = ∑ ik : Fin (p - 1) × Fin (q - 1),
        (cycBasis p q).repr z ik • cycBasis p q ik :=
      ((cycBasis p q).sum_repr z).symm
    have h0 : ∑ ik : Fin (p - 1) × Fin (q - 1),
        (cycBasis p q).repr z ik •
          ((eta p q ^ q) ^ (ik.1 : ℕ) * (eta p q ^ p) ^ (ik.2 : ℕ)) = 0 := by
      have := congrArg (cycEmb p q) hexp.symm
      rw [map_sum] at this
      rw [← hz, ← this]
      refine Finset.sum_congr rfl fun ik _ => ?_
      rw [map_zsmul, hmap]
    have hcoeff := Fintype.linearIndependent_iff.mp
      (monomials_linearIndependent p q hpq) _ h0
    rw [hexp]
    refine Finset.sum_eq_zero fun ik _ => ?_
    rw [hcoeff ik, zero_smul]
  intro x y hxy
  have h := hker (x - y) (by rw [map_sub, hxy, sub_self])
  exact sub_eq_zero.mp h

end Independence

section Consequences

variable (hpq : p ≠ q)

include hpq in
/-- **The model is an integral domain** (distinct primes): it embeds
into the cyclotomic field `ℚ(ζ_pq)`. -/
theorem isDomain_cycPQ : IsDomain (CycPQ p q) :=
  Function.Injective.isDomain (cycEmb p q) (cycEmb_injective p q hpq)

include hpq in
/-- `ζ_p` is a genuine primitive `p`-th root of unity in the model. -/
theorem isPrimitiveRoot_zetaP : IsPrimitiveRoot (zetaP p q) p := by
  refine IsPrimitiveRoot.of_map_of_injective ?_ (cycEmb_injective p q hpq)
  rw [cycEmb_zetaP]
  exact etaQ_pow_spec p q

include hpq in
/-- `ζ_q` is a genuine primitive `q`-th root of unity in the model. -/
theorem isPrimitiveRoot_zetaQ : IsPrimitiveRoot (zetaQ p q) q := by
  refine IsPrimitiveRoot.of_map_of_injective ?_ (cycEmb_injective p q hpq)
  rw [cycEmb_zetaQ]
  exact etaP_pow_spec p q

/-- **Integers are faithful in the model**: divisibility of integer
constants in `ℤ[ζ_p, ζ_q]` is ordinary divisibility — this converts
Lemma 4.4.3's ring-form hypothesis into the book's `n ∤ m`.  (No
distinctness of `p, q` needed: this is pure content bookkeeping.) -/
theorem natCast_dvd_natCast_iff (n m : ℕ) :
    (n : CycPQ p q) ∣ (m : CycPQ p q) ↔ n ∣ m := by
  constructor
  · intro h
    have hp2 := (Fact.out (p := p.Prime)).two_le
    have hq2 := (Fact.out (p := q.Prime)).two_le
    -- read off the `(0,0)` coordinate
    have hone : (1 : CycPQ p q)
        = cycBasis p q (⟨0, by omega⟩, ⟨0, by omega⟩) := by
      rw [cycBasis_apply]
      simp
    have hm : (m : CycPQ p q)
        = (m : ℤ) • cycBasis p q (⟨0, by omega⟩, ⟨0, by omega⟩) := by
      rw [← hone, zsmul_eq_mul, mul_one]
      push_cast
      rfl
    rw [natCast_dvd_iff_dvd_content] at h
    have hcoord := h.trans
      (Finset.gcd_dvd (Finset.mem_univ (⟨0, by omega⟩, ⟨0, by omega⟩)))
    rw [hm, map_smul] at hcoord
    simpa [Basis.repr_self] using hcoord
  · intro h
    exact_mod_cast Nat.cast_dvd_cast (α := CycPQ p q) h

end Consequences

end CP

end Azurite
