/-
  Crandall–Pomerance, equation (4.21) — the order-climbing engines of
  the proof of Theorem 4.4.6 (correctness of the Gauss sums primality
  test): for `n` composite with least prime factor `r` surviving
  steps 1–4 of Algorithm 4.4.5,

    `p^(w(p)) ∣ r^(p−1) − 1`  for each prime `p ∣ I`.       (4.21)

  Both cases of the book's argument are pure statements about orders
  in a commutative monoid — here `M` stands for the multiplicative
  structure of `ℤ[ζ_p, ζ_q]/(r)`, `G` for the Gauss sum's image, `ζ`
  for the `p`-th root's image, and `N` for `r^(p−1) − 1`; the
  hypotheses `G^N = ζ^(j₀)` and `G^(pN) = 1` are what Lemma 4.4.2
  provides mod `r` (with `χ(r)` a `p`-th root of unity), and the
  instantiation happens when the algorithm's correctness theorem is
  assembled.

  * Case `l(p,q) ≠ 0` (`eq_4_21_of_ne_one`): `G^(p^w u) = ζ^l` with
    `p ∤ l` forces the `p`-adic valuation of `h = ord G` to be
    exactly `w + 1`; with `h ∣ pN` this gives `p^w ∣ N`.
  * Case all `l(p,q) = 0` (`eq_4_21_of_forall_ne`): here
    `G^(p^w u) = 1` gives `v_p(h) ≤ w`, the step-5 coprime check —
    `G^(p^(w−1) u)` is NO power of `ζ` — gives `v_p(h) = w` exactly,
    AND forces any `G`-power that is a `ζ`-power to be `1`: an
    order-`p` value `G^N = ζ^(j₀) ≠ 1` would put `ζ^(j₀)` in the
    unique order-`p` subgroup of the cyclic group generated by `G`,
    making `G^(p^(w−1) u)` a `ζ`-power (the linear congruence
    `Nk ≡ p^(w−1)u (mod h)` is solvable since `gcd(N, h) = h/p`
    divides `p^(w−1)u`) — contradiction.  So `ζ^(j₀) = 1`, whence
    `h ∣ N` and `p^w ∣ N`.

  The linear-congruence solver `exists_mul_modEq`
  (`Nk ≡ c (mod h)` solvable when `gcd(N, h) ∣ c`, by Bézout) is
  general-purpose.
-/
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.Int.GCD
import Mathlib.Tactic.Ring

namespace Azurite

namespace CP

/-- The linear congruence `N·k ≡ c (mod h)` is solvable when
`gcd(N, h) ∣ c` (Bézout). -/
theorem exists_mul_modEq (h N c : ℕ) (hh : 0 < h)
    (hdvd : Nat.gcd N h ∣ c) : ∃ k : ℕ, N * k ≡ c [MOD h] := by
  obtain ⟨c', rfl⟩ := hdvd
  have hbez : (Nat.gcd N h : ℤ) = N * Nat.gcdA N h + h * Nat.gcdB N h :=
    Nat.gcd_eq_gcd_ab N h
  set z : ℤ := Nat.gcdA N h * c' with hz
  have hh0 : ((h : ℤ)) ≠ 0 := by exact_mod_cast hh.ne'
  refine ⟨(z % (h : ℤ)).toNat, ?_⟩
  rw [Nat.ModEq.comm, Nat.modEq_iff_dvd]
  push_cast
  rw [Int.toNat_of_nonneg (Int.emod_nonneg z hh0)]
  refine ⟨-(Nat.gcdB N h * c') - N * (z / h), ?_⟩
  rw [Int.emod_def, hbez, hz]
  ring

section Engines

variable {M : Type _} [CommMonoid M] {G ζ : M} {p : ℕ}

/-- The valuation of a product at a prime, pointwise. -/
private theorem factorization_mul_apply {a b q : ℕ} (ha : a ≠ 0)
    (hb : b ≠ 0) : (a * b).factorization q
      = a.factorization q + b.factorization q := by
  rw [Nat.factorization_mul ha hb]
  rfl

/-- **(4.21), the case `l(p,q) ≠ 0`**: a `G`-power equal to a
nontrivial power of the `p`-th root `ζ` pins the `p`-adic valuation
of `ord G` at `w + 1`; then `G^(pN) = 1` gives `p^w ∣ N`. -/
theorem eq_4_21_of_ne_one {w u l N : ℕ} (hp : p.Prime)
    (hζ : orderOf ζ = p) (hl : ¬p ∣ l)
    (h1 : G ^ (p ^ w * u) = ζ ^ l) (h42 : G ^ (p * N) = 1) :
    p ^ w ∣ N := by
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · exact dvd_zero _
  have hfin : IsOfFinOrder G :=
    isOfFinOrder_iff_pow_eq_one.mpr
      ⟨p * N, Nat.mul_pos hp.pos hN, h42⟩
  have hζfin : IsOfFinOrder ζ := by
    rw [← orderOf_pos_iff, hζ]
    exact hp.pos
  have hpos : 0 < orderOf G := hfin.orderOf_pos
  set h := orderOf G with hhdef
  -- the order of `G^(p^w u)` is `p`
  have hord1 : h / Nat.gcd h (p ^ w * u) = p := by
    rw [← hfin.orderOf_pow G (p ^ w * u), h1, hζfin.orderOf_pow, hζ,
      Nat.Coprime.gcd_eq_one ((Nat.Prime.coprime_iff_not_dvd hp).mpr hl),
      Nat.div_one]
  have hmul : h = Nat.gcd h (p ^ w * u) * p :=
    Nat.eq_mul_of_div_eq_right (Nat.gcd_dvd_left h _) hord1
  have hg0 : Nat.gcd h (p ^ w * u) ≠ 0 :=
    fun h0 => hpos.ne' (Nat.eq_zero_of_gcd_eq_zero_left h0)
  -- valuation bookkeeping: `v_p(h) = v_p(gcd) + 1` and
  -- `min (v_p h) w ≤ v_p(gcd)` force `v_p(h) ≥ w + 1`
  have hvh : h.factorization p
      = (Nat.gcd h (p ^ w * u)).factorization p + 1 := by
    conv_lhs => rw [hmul]
    rw [factorization_mul_apply hg0 hp.pos.ne', hp.factorization,
      Finsupp.single_eq_same]
  have hminle : min (h.factorization p) w
      ≤ (Nat.gcd h (p ^ w * u)).factorization p := by
    have hdg : p ^ min (h.factorization p) w ∣ Nat.gcd h (p ^ w * u) :=
      Nat.dvd_gcd
        ((pow_dvd_pow p (min_le_left _ _)).trans
          ((Nat.Prime.pow_dvd_iff_le_factorization hp hpos.ne').mpr le_rfl))
        ((pow_dvd_pow p (min_le_right _ _)).trans (dvd_mul_right _ u))
    exact (Nat.Prime.pow_dvd_iff_le_factorization hp hg0).mp hdg
  have hval : w + 1 ≤ h.factorization p := by omega
  have hdvd : p ^ (w + 1) ∣ h :=
    (Nat.Prime.pow_dvd_iff_le_factorization hp hpos.ne').mpr hval
  have hdvd2 : p ^ (w + 1) ∣ p * N :=
    hdvd.trans (orderOf_dvd_of_pow_eq_one h42)
  rw [pow_succ', Nat.mul_dvd_mul_iff_left hp.pos] at hdvd2
  exact hdvd2

/-- **(4.21), the case all `l(p,q) = 0`**: with `G^(p^w u) = 1` and
the step-5 coprime check (`G^(p^(w−1) u)` is no `ζ`-power), any
`G`-power equal to a `ζ`-power must equal `1`; applied to
`G^N = ζ^(j₀)` from Lemma 4.4.2 this gives `ζ^(j₀) = 1` and
`p^w ∣ N`. -/
theorem eq_4_21_of_forall_ne {w u N j₀ : ℕ} (hp : p.Prime)
    (hζ : orderOf ζ = p) (hu : ¬p ∣ u) (hw : 0 < w)
    (h1 : G ^ (p ^ w * u) = 1)
    (h5 : ∀ j, G ^ (p ^ (w - 1) * u) ≠ ζ ^ j)
    (h42 : G ^ N = ζ ^ j₀) :
    p ^ w ∣ N ∧ ζ ^ j₀ = 1 := by
  have hu0 : u ≠ 0 := fun h => hu (h ▸ dvd_zero p)
  have hpw0 : p ^ w * u ≠ 0 := Nat.mul_ne_zero (pow_ne_zero w hp.pos.ne') hu0
  have hpw10 : p ^ (w - 1) * u ≠ 0 :=
    Nat.mul_ne_zero (pow_ne_zero _ hp.pos.ne') hu0
  have hfin : IsOfFinOrder G :=
    isOfFinOrder_iff_pow_eq_one.mpr
      ⟨p ^ w * u, Nat.pos_of_ne_zero hpw0, h1⟩
  have hζfin : IsOfFinOrder ζ := by
    rw [← orderOf_pos_iff, hζ]
    exact hp.pos
  have hpos : 0 < orderOf G := hfin.orderOf_pos
  set h := orderOf G with hhdef
  have hdvd1 : h ∣ p ^ w * u := orderOf_dvd_of_pow_eq_one h1
  have hndvd : ¬h ∣ p ^ (w - 1) * u := by
    intro hd
    exact h5 0 (by
      rw [pow_zero]
      exact orderOf_dvd_iff_pow_eq_one.mp hd)
  -- valuation of an exponent product
  have hvexp : ∀ (v : ℕ) (q : ℕ), (p ^ v * u).factorization q
      = (if p = q then v else 0) + u.factorization q := by
    intro v q
    rw [factorization_mul_apply (pow_ne_zero v hp.pos.ne') hu0,
      hp.factorization_pow, Finsupp.single_apply]
  have hvu : u.factorization p = 0 := Nat.factorization_eq_zero_of_not_dvd hu
  have hle : ∀ q, h.factorization q ≤ (p ^ w * u).factorization q :=
    fun q => (Nat.factorization_le_iff_dvd hpos.ne' hpw0).mpr hdvd1 q
  -- `v_p(h) = w` exactly (`≤` from `h ∣ p^w u`, `≥` from `¬ ∣`)
  have hvalp : h.factorization p = w := by
    have hub : h.factorization p ≤ w := by
      have := hle p
      rw [hvexp w p, ite_eq_left rfl, hvu] at this
      omega
    by_contra hne
    refine hndvd ((Nat.factorization_le_iff_dvd hpos.ne' hpw10).mp ?_)
    intro q
    rw [hvexp (w - 1) q]
    by_cases hq : q = p
    · subst hq
      rw [ite_eq_left rfl, hvu]
      omega
    · have := hle q
      rw [hvexp w q, ite_eq_right (Ne.symm hq)] at this
      rw [ite_eq_right (Ne.symm hq)]
      omega
  have hpwh : p ^ w ∣ h :=
    (Nat.Prime.pow_dvd_iff_le_factorization hp hpos.ne').mpr hvalp.ge
  -- the heart: `ζ^(j₀) = 1`
  have hζ1 : ζ ^ j₀ = 1 := by
    by_contra hne
    have hpj : ¬p ∣ j₀ := by
      rintro ⟨t, rfl⟩
      exact hne (by rw [pow_mul, ← hζ, pow_orderOf_eq_one, one_pow])
    -- `orderOf (G^N) = p`, so `h = gcd(h, N) · p`
    have hordN : h / Nat.gcd h N = p := by
      rw [← hfin.orderOf_pow G N, h42, hζfin.orderOf_pow, hζ,
        Nat.Coprime.gcd_eq_one ((Nat.Prime.coprime_iff_not_dvd hp).mpr hpj),
        Nat.div_one]
    have hmul : h = Nat.gcd h N * p :=
      Nat.eq_mul_of_div_eq_right (Nat.gcd_dvd_left h N) hordN
    have hg0 : Nat.gcd h N ≠ 0 :=
      fun h0 => hpos.ne' (Nat.eq_zero_of_gcd_eq_zero_left h0)
    -- `gcd(h, N) ∣ p^(w−1) u`
    have hdc : Nat.gcd h N ∣ p ^ (w - 1) * u := by
      refine (Nat.factorization_le_iff_dvd hg0 hpw10).mp ?_
      intro q
      have hgq : h.factorization q
          = (Nat.gcd h N).factorization q + (if p = q then 1 else 0) := by
        conv_lhs => rw [hmul]
        rw [factorization_mul_apply hg0 hp.pos.ne', hp.factorization,
          Finsupp.single_apply]
      have hlq := hle q
      rw [hvexp w q] at hlq
      rw [hvexp (w - 1) q]
      by_cases hq : q = p
      · subst hq
        rw [ite_eq_left rfl] at hgq
        rw [ite_eq_left rfl, hvu]
        rw [hvalp] at hgq
        omega
      · rw [ite_eq_right (Ne.symm hq)] at hlq ⊢
        rw [ite_eq_right (Ne.symm hq)] at hgq
        omega
    obtain ⟨k, hk⟩ := exists_mul_modEq h N (p ^ (w - 1) * u) hpos
      (by rw [Nat.gcd_comm]; exact hdc)
    refine h5 (j₀ * k) ?_
    have hGk : G ^ (N * k) = G ^ (p ^ (w - 1) * u) :=
      (hfin.pow_eq_pow_iff_modEq).mpr hk
    rw [← hGk, pow_mul, h42, ← pow_mul]
  refine ⟨?_, hζ1⟩
  have hG1 : G ^ N = 1 := by rw [h42, hζ1]
  exact hpwh.trans (orderOf_dvd_of_pow_eq_one hG1)

end Engines

end CP

end Azurite
