/-
Copyright © 2026 Mikhail Hogrefe

This file is part of Azurite.

Azurite is free software: you can redistribute it and/or modify it under the terms of the Apache
License, Version 2.0. See <https://www.apache.org/licenses/LICENSE-2.0>.
-/

import Azurite.BasuPollackRoy.Chapter4.Section4_4.Theorem_4_61

/-!
# BPR Corollary 4.71: the ascending chain condition

An ascending chain of ideals `I₁ ⊆ I₂ ⊆ ⋯` of `K[X₁, …, X_k]` stabilizes: there is some `n`
such that `I_m = I_n` for all `m > n`. Following BPR, the union `J = ⋃ᵢ Iᵢ` is an ideal, hence
finitely generated by Theorem 4.61; the finitely many generators all belong to some `I_N`, so
`I_N = J`, and the chain is constant from `N` on.
-/

namespace Azurite.BPR.Chapter4

open MvPolynomial

variable {k : ℕ} {K : Type*} [Field K]

/-- **BPR Corollary 4.71 (ascending chain condition).** Every ascending chain of ideals
`I₁ ⊆ I₂ ⊆ ⋯` of `K[X₁, …, X_k]` stabilizes: there is an `n` with `I_m = I_n` for all
`m > n`. -/
theorem corollary_4_71 (I : ℕ → Ideal (MvPolynomial (Fin k) K)) (hI : Monotone I) :
    ∃ n : ℕ, ∀ m : ℕ, m > n → I m = I n := by
  classical
  have hdir : Directed (· ≤ ·) I := hI.directed_le
  -- `J = ⋃ᵢ Iᵢ` is finitely generated by Theorem 4.61.
  obtain ⟨P, hP⟩ := theorem_4_61 (⨆ i, I i)
  -- Each generator lies in `J`, hence in some `I i` (the family is directed).
  have hmem : ∀ p ∈ P, ∃ i, p ∈ I i := by
    intro p hp
    have hpJ : p ∈ ⨆ i, I i := by
      rw [hP]; simp only [idealOfPolys]
      exact Ideal.subset_span (Finset.mem_coe.mpr hp)
    exact (Submodule.mem_iSup_of_directed I hdir).mp hpJ
  choose idx hidx using hmem
  -- `N` bounds all the chosen indices, so every generator lies in `I N`.
  set N := P.attach.sup (fun p => idx p.1 p.2) with hN
  have hNJ : I N = ⨆ i, I i := by
    refine le_antisymm (le_iSup I N) ?_
    rw [hP]; simp only [idealOfPolys, Ideal.span_le]
    intro x hx
    rw [Finset.mem_coe] at hx
    have hle : idx x hx ≤ N :=
      Finset.le_sup (f := fun p => idx p.1 p.2) (Finset.mem_attach P ⟨x, hx⟩)
    exact hI hle (hidx x hx)
  -- From `N` on, `I N ⊆ I m ⊆ J = I N`, so the chain is constant.
  refine ⟨N, fun m hm => ?_⟩
  have h2 : I m ≤ I N := by rw [hNJ]; exact le_iSup I m
  exact le_antisymm h2 (hI hm.le)

end Azurite.BPR.Chapter4
