/-
Copyright © 2026 Mikhail Hogrefe

This file is part of Azurite.

Azurite is free software: you can redistribute it and/or modify it under the terms of the Apache
License, Version 2.0. See <https://www.apache.org/licenses/LICENSE-2.0>.
-/

import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# BPR §4.4: the ideal generated by a finite set of polynomials

To a finite set of polynomials `𝒫 ⊆ K[X₁, …, X_k]` is associated `Ideal(𝒫, K)`, the ideal
generated by `𝒫`:
`Ideal(𝒫, K) = {∑_{P ∈ 𝒫} A_P · P | A_P ∈ K[X₁, …, X_k]}` (`idealOfPolys`, `mem_idealOfPolys_iff`).

A polynomial in `Ideal(𝒫, K)` vanishes at every point of `Zer(𝒫, Cᵏ)` (the common zero set of
`𝒫` in `Cᵏ`, for any `K`-algebra `C`): `aeval_eq_zero_of_mem_idealOfPolys`.
-/

namespace Azurite.BPR.Chapter4

open MvPolynomial

variable {k : ℕ} {K : Type*} [CommRing K]

/-- **BPR `Ideal(𝒫, K)`**: the ideal generated by a finite set `𝒫` of polynomials in
`K[X₁, …, X_k]`. -/
noncomputable def idealOfPolys (P : Finset (MvPolynomial (Fin k) K)) :
    Ideal (MvPolynomial (Fin k) K) :=
  Ideal.span (↑P : Set (MvPolynomial (Fin k) K))

/-- `Ideal(𝒫, K) = {∑_{P ∈ 𝒫} A_P · P | A_P ∈ K[X₁, …, X_k]}`. -/
theorem mem_idealOfPolys_iff (P : Finset (MvPolynomial (Fin k) K))
    (f : MvPolynomial (Fin k) K) :
    f ∈ idealOfPolys P
      ↔ ∃ A : MvPolynomial (Fin k) K → MvPolynomial (Fin k) K, ∑ p ∈ P, A p * p = f := by
  rw [idealOfPolys]
  constructor
  · intro hf
    obtain ⟨c, _, hc⟩ := Submodule.mem_span_finset.mp hf
    exact ⟨c, by simpa only [smul_eq_mul] using hc⟩
  · rintro ⟨A, rfl⟩
    exact Submodule.sum_mem _ fun p hp =>
      Ideal.mul_mem_left _ _ (Ideal.subset_span (Finset.mem_coe.mpr hp))

variable {C : Type*} [CommRing C] [Algebra K C]

/-- **A polynomial in `Ideal(𝒫, K)` vanishes at every common zero of `𝒫` in `Cᵏ`.** If
`f ∈ Ideal(𝒫, K)` and `x ∈ Cᵏ` is a common zero of `𝒫` (i.e. `x ∈ Zer(𝒫, Cᵏ)`), then
`f(x) = 0`. -/
theorem aeval_eq_zero_of_mem_idealOfPolys {P : Finset (MvPolynomial (Fin k) K)}
    {f : MvPolynomial (Fin k) K} (hf : f ∈ idealOfPolys P) (x : Fin k → C)
    (hx : ∀ p ∈ P, MvPolynomial.aeval x p = 0) :
    MvPolynomial.aeval x f = 0 := by
  rw [idealOfPolys] at hf
  induction hf using Submodule.span_induction with
  | mem q hq => exact hx q (Finset.mem_coe.mp hq)
  | zero => simp
  | add a b _ _ ha hb => rw [map_add, ha, hb, add_zero]
  | smul a q _ hq => rw [smul_eq_mul, map_mul, hq, mul_zero]

end Azurite.BPR.Chapter4
