import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Algebra.MvPolynomial.Division
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.Tactic.LinearCombination
import Azurite.BasuPollackRoy.Chapter1.Section1_2.Definition1_13

/-!
# BPR §4.4: the univariate case `k = 1`

When `k = 1`, the ideal generated by a finite set `𝒫 ⊆ K[X]` is principal — generated by a
single polynomial `g` (`idealOfPolys_univariate_isPrincipal`) — and that generator is a
greatest common divisor of `𝒫`: it divides every polynomial in `𝒫`, and every common divisor
of `𝒫` divides it (`idealOfPolys_univariate_eq_span_gcd`). This is no longer true for a
general `k` (e.g. the ideal `(X₁, X₂)` of `K[X₁, X₂]` is not principal).
-/

namespace Azurite.BPR.Chapter4

open Polynomial

variable {K : Type*} [Field K]

/-- **`k = 1`: the ideal is principal.** Over a field, `K[X]` is a principal ideal domain, so
the ideal generated by a finite set `𝒫 ⊆ K[X]` is generated by a single polynomial. -/
theorem idealOfPolys_univariate_isPrincipal (P : Finset K[X]) :
    (Ideal.span (↑P : Set K[X])).IsPrincipal :=
  IsPrincipalIdealRing.principal _

/-- **`k = 1`: the generator is the gcd.** The ideal generated by `𝒫 ⊆ K[X]` is generated by
the greatest common divisor `listGcd 𝒫` of the polynomials in `𝒫` (Azurite's `IsListGCD`,
BPR Definition 1.13). -/
theorem idealOfPolys_univariate_eq_span_gcd (P : Finset K[X]) :
    Ideal.span (↑P : Set K[X]) = Ideal.span {Azurite.BPR.listGcd P.toList} := by
  have hgcd := Azurite.BPR.listGcd_isListGCD P.toList
  apply le_antisymm
  · -- span ↑P ≤ span {listGcd}: `listGcd 𝒫` divides every `p ∈ 𝒫`
    rw [Ideal.span_le]
    intro p hp
    exact Ideal.mem_span_singleton.mpr (hgcd.1 p (Finset.mem_toList.mpr (Finset.mem_coe.mp hp)))
  · -- span {listGcd} ≤ span ↑P: `listGcd 𝒫 ∈ Ideal(𝒫, K)`
    rw [Ideal.span_singleton_le_iff_mem]
    haveI : (Ideal.span (↑P : Set K[X])).IsPrincipal := IsPrincipalIdealRing.principal _
    obtain ⟨g, hg⟩ : ∃ g, Ideal.span (↑P : Set K[X]) = Ideal.span {g} :=
      ⟨_, (Submodule.IsPrincipal.span_singleton_generator _).symm⟩
    rw [hg, Ideal.mem_span_singleton]
    -- the generator `g` divides every `p ∈ 𝒫`, hence (gcd universal property) divides `listGcd 𝒫`
    refine hgcd.2 g fun p hp => ?_
    have hmem : p ∈ Ideal.span (↑P : Set K[X]) :=
      Ideal.subset_span (Finset.mem_coe.mpr (Finset.mem_toList.mp hp))
    rw [hg, Ideal.mem_span_singleton] at hmem
    exact hmem

/-- **`k ≥ 2`: principality fails.** The ideal `(X₀, X₁)` of `K[X₀, X₁]` is not principal — a
concrete witness that the univariate result does not extend to several variables. -/
theorem span_X_pair_not_isPrincipal :
    ¬ (Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1} :
        Set (MvPolynomial (Fin 2) K))).IsPrincipal := by
  intro hprinc
  -- `X 0` does not divide `X 1` (evaluate at the point `(0, 1)`).
  have hX0_ndvd_X1 : ¬ (MvPolynomial.X 0 ∣ (MvPolynomial.X 1 : MvPolynomial (Fin 2) K)) := by
    rintro ⟨h, hh⟩
    have key := congrArg (MvPolynomial.eval (![0, 1] : Fin 2 → K)) hh
    rw [map_mul, MvPolynomial.eval_X, MvPolynomial.eval_X] at key
    simp at key
  -- The ideal is proper: every element vanishes at `0`, but `1` does not.
  have hne : (Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1} :
      Set (MvPolynomial (Fin 2) K))) ≠ ⊤ := by
    rw [Ideal.ne_top_iff_one]
    intro h
    have key : ∀ p ∈ Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1} :
        Set (MvPolynomial (Fin 2) K)), MvPolynomial.eval (0 : Fin 2 → K) p = 0 := by
      intro p hp
      induction hp using Submodule.span_induction with
      | mem q hq =>
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
          rcases hq with rfl | rfl <;> simp
      | zero => simp
      | add a b _ _ ha hb => rw [map_add, ha, hb, add_zero]
      | smul a q _ hq => rw [smul_eq_mul, map_mul, hq, mul_zero]
    have := key 1 h
    simp at this
  -- Extract a generator `g`.
  haveI := hprinc
  obtain ⟨g, hg⟩ : ∃ g, Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1} :
      Set (MvPolynomial (Fin 2) K)) = Ideal.span {g} :=
    ⟨_, (Submodule.IsPrincipal.span_singleton_generator _).symm⟩
  have hgX0 : g ∣ MvPolynomial.X 0 := by
    have hmem : (MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ∈ Ideal.span
        ({MvPolynomial.X 0, MvPolynomial.X 1} : Set _) := Ideal.subset_span (by simp)
    rwa [hg, Ideal.mem_span_singleton] at hmem
  have hgX1 : g ∣ MvPolynomial.X 1 := by
    have hmem : (MvPolynomial.X 1 : MvPolynomial (Fin 2) K) ∈ Ideal.span
        ({MvPolynomial.X 0, MvPolynomial.X 1} : Set _) := Ideal.subset_span (by simp)
    rwa [hg, Ideal.mem_span_singleton] at hmem
  -- `g` divides the prime `X 0`, so it is a unit (else `X 0 ∣ g ∣ X 1`, impossible).
  have hgunit : IsUnit g := by
    by_contra hgnu
    obtain ⟨h0, hh0⟩ := hgX0
    have hp : Prime (MvPolynomial.X 0 : MvPolynomial (Fin 2) K) := MvPolynomial.X_prime
    have hdvd : MvPolynomial.X 0 ∣ g * h0 := ⟨1, by rw [mul_one, hh0]⟩
    rcases hp.2.2 g h0 hdvd with hX0g | hX0h0
    · exact hX0_ndvd_X1 (hX0g.trans hgX1)
    · obtain ⟨m, hm⟩ := hX0h0
      have hzero : MvPolynomial.X 0 * (1 - g * m) = 0 := by linear_combination hh0 + g * hm
      rcases mul_eq_zero.mp hzero with h | h
      · exact hp.ne_zero h
      · exact hgnu (IsUnit.of_mul_eq_one m (sub_eq_zero.mp h).symm)
  -- A unit generator would make the ideal everything, contradicting properness.
  exact hne (by rw [hg, Ideal.span_singleton_eq_top]; exact hgunit)

end Azurite.BPR.Chapter4
