import Azurite.BasuPollackRoy.Chapter2.Section2_1.HasNoNontrivialRealAlgebraicExtension
import Azurite.BasuPollackRoy.Chapter2.Section2_1.RealField
import Azurite.BasuPollackRoy.Chapter2.Section2_1.Theorem_2_11_d_a
import Azurite.BasuPollackRoy.Chapter2.Section2_1.Proposition_2_8
import Azurite.BasuPollackRoy.Chapter2.Section2_1.Cones
import Mathlib.Order.Zorn
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Real closure of a formally real field — existence

BPR states (Section 2.1) that any ordered field has a real closure: a real
closed field, algebraic over it, extending it. This file proves the
**existence** half over an arbitrary formally real base field `F`: inside
any algebraically closed field `C ⊇ F` of characteristic zero there is a
real closed intermediate field `F ⊆ R ⊆ C`. Taking `C = AlgebraicClosure F`
gives a real closed field algebraic over `F`.

This generalizes `Theorem 2.31` (which is the case `F = ℚ`) from the base
field `ℚ` to an arbitrary formally real base, reusing the same Zorn
argument: a maximal semireal intermediate field over `F` has no nontrivial
real algebraic extension (`IsAlgClosed.lift`), hence is real closed by
Theorem 2.11 (d ⇒ a).
-/

namespace Azurite.BPR.RealClosure

open Polynomial IntermediateField

/-- Sums of squares are preserved by ring homomorphisms. -/
private lemma isSumSq_map {A B : Type*} [Ring A] [Ring B]
    (f : A →+* B) {x : A} (h : IsSumSq x) : IsSumSq (f x) := by
  induction h with
  | zero => exact map_zero f ▸ .zero
  | sq_add a _ ih => rw [map_add, map_mul]; exact .sq_add (f a) ih

/-! ### The `√a` adjoin: weighted decomposition

For the *order-compatible* real closure we maximize fields where the cone
generated by `F`'s positive cone stays proper, and need: adjoining `√a`
for `a` in the cone preserves this. The heart is that if `-1 = ∑ γᵢ zᵢ²`
(cone weights `γᵢ`) holds in `R[√a] = AdjoinRoot(X²-a)`, then taking the
"free part" (coefficient of `1` in the basis `{1, √a}`) gives
`-1 = ∑ γᵢ(xᵢ² + a yᵢ²)` in `R` — a `C`-weighted generalization of
`Theorem2_11.decompose_neg_one_in_adjoinRoot`. -/

open Azurite.BPR.Theorem2_11

/-- **Weighted decomposition in `R[√a]`.** If `-1 = ∑ γᵢ · zᵢ²` in
`AdjoinRoot(X²-a)` with weights `γᵢ ∈ R`, then `-1 = ∑ γᵢ(xᵢ² + a yᵢ²)`
in `R`, where `zᵢ = xᵢ + yᵢ√a`. (The √a-component vanishes since `-1 ∈ R`.) -/
theorem weighted_decompose {R : Type*} [Field R] {a : R} [Fact (Irreducible (sqSubC a))]
    {n : ℕ} (γ : Fin n → R) (z : Fin n → AdjoinRoot (sqSubC a))
    (hsum : -1 = ∑ i, algebraMap R _ (γ i) * (z i) ^ 2) :
    ∃ x y : Fin n → R, (-1 : R) = ∑ i, γ i * (x i ^ 2 + a * y i ^ 2) := by
  choose x y hxy using fun i => repr_exists_sq_sub a (z i)
  set rt := AdjoinRoot.root (sqSubC a)
  have hrt2 : rt ^ 2 = algebraMap R _ a := root_sq_sub_C a
  have hsq : ∀ i, algebraMap R _ (γ i) * (z i) ^ 2 =
      algebraMap R _ (γ i * (x i ^ 2 + a * y i ^ 2)) +
      algebraMap R _ (γ i * (2 * (x i * y i))) * rt := by
    intro i
    rw [hxy i, pow_two]
    have step1 : (algebraMap R (AdjoinRoot (sqSubC a)) (x i) + algebraMap R _ (y i) * rt) *
        (algebraMap R _ (x i) + algebraMap R _ (y i) * rt) =
        algebraMap R _ (x i) * algebraMap R _ (x i) +
        algebraMap R _ (y i) * algebraMap R _ (y i) * (rt * rt) +
        (algebraMap R _ (x i) * algebraMap R _ (y i) +
         algebraMap R _ (x i) * algebraMap R _ (y i)) * rt := by ring
    rw [step1, show rt * rt = rt ^ 2 from (pow_two rt).symm, hrt2]
    simp only [map_add, map_mul, map_ofNat, map_pow]; ring
  have key : (-1 : AdjoinRoot (sqSubC a)) =
      algebraMap R _ (∑ i, γ i * (x i ^ 2 + a * y i ^ 2)) +
      algebraMap R _ (∑ i, γ i * (2 * (x i * y i))) * rt := by
    rw [hsum]; simp_rw [hsq, map_sum, Finset.sum_add_distrib, Finset.sum_mul]
  have hdiff : algebraMap R _ (-1 - ∑ i, γ i * (x i ^ 2 + a * y i ^ 2)) +
      algebraMap R _ (0 - ∑ i, γ i * (2 * (x i * y i))) * rt = 0 := by
    rw [map_sub, map_sub, map_neg, map_one, map_zero]; linear_combination key
  obtain ⟨heq1, _⟩ := repr_unique_sq_sub a hdiff
  exact ⟨x, y, sub_eq_zero.mp heq1⟩

/-- Multiplicative closure of `(C-image ∪ squares)` consists of `γ·w²`. -/
private theorem mul_closure_form {B E : Type*} [CommRing B] [CommRing E] [Algebra B E]
    (C : Subsemiring B) (t : E)
    (ht : t ∈ Submonoid.closure ((algebraMap B E '' (C : Set B)) ∪ {x | IsSquare x})) :
    ∃ γ ∈ C, ∃ w, t = algebraMap B E γ * w ^ 2 := by
  induction ht using Submonoid.closure_induction with
  | mem x hx =>
    rcases hx with ⟨c, hc, rfl⟩ | ⟨w, rfl⟩
    · exact ⟨c, hc, 1, by simp⟩
    · exact ⟨1, C.one_mem, w, by simp [pow_two]⟩
  | one => exact ⟨1, C.one_mem, 1, by simp⟩
  | mul x y _ _ ihx ihy =>
    obtain ⟨γ, hγ, w, rfl⟩ := ihx
    obtain ⟨δ, hδ, v, rfl⟩ := ihy
    exact ⟨γ * δ, C.mul_mem hγ hδ, w * v, by rw [map_mul]; ring⟩

/-- Additive closure of those `γ·w²` gives a finite sum `∑ γᵢ wᵢ²`. -/
private theorem add_closure_form {B E : Type*} [CommRing B] [CommRing E] [Algebra B E]
    (C : Subsemiring B) (t : E)
    (ht : t ∈ AddSubmonoid.closure (Submonoid.closure
      ((algebraMap B E '' (C : Set B)) ∪ {x | IsSquare x}) : Set E)) :
    ∃ (n : ℕ) (γ : Fin n → B) (w : Fin n → E),
      (∀ i, γ i ∈ C) ∧ t = ∑ i, algebraMap B E (γ i) * (w i) ^ 2 := by
  induction ht using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨γ, hγ, w, rfl⟩ := mul_closure_form C x hx
    exact ⟨1, fun _ => γ, fun _ => w, fun _ => hγ, by simp⟩
  | zero => exact ⟨0, Fin.elim0, Fin.elim0, fun i => i.elim0, by simp⟩
  | add x y _ _ ihx ihy =>
    obtain ⟨n, γ, w, hγ, rfl⟩ := ihx
    obtain ⟨m, δ, v, hδ, rfl⟩ := ihy
    refine ⟨n + m, Fin.append γ δ, Fin.append w v, ?_, ?_⟩
    · exact fun i => Fin.addCases (fun j => by simpa using hγ j) (fun j => by simpa using hδ j) i
    · rw [Fin.sum_univ_add]; simp [Fin.append_left, Fin.append_right]

/-- **The `√a` adjoin.** If `C` is a proper cone of `R` (contains all
squares, not `-1`) and `a ∈ C` is not a square, then the cone generated by
`C` in `R[√a] = AdjoinRoot(X²-a)` is still proper — i.e. `-1` is not in the
subsemiring generated by the image of `C` together with all squares. This
is what lets `√a` be adjoined while keeping the order compatible. -/
theorem adjoin_compatible {R : Type*} [Field R] {a : R} (C : Subsemiring R)
    (hCsq : ∀ x : R, x * x ∈ C) (ha : a ∈ C) (hC : (-1 : R) ∉ C) (ha_sq : ¬ IsSquare a) :
    (-1 : AdjoinRoot (sqSubC a)) ∉ Subsemiring.closure
      ((algebraMap R (AdjoinRoot (sqSubC a)) '' (C : Set R)) ∪ {x | IsSquare x}) := by
  intro hmem
  haveI : Fact (Irreducible (sqSubC a)) := ⟨irred_X_sq_sub_C ha_sq⟩
  rw [Subsemiring.mem_closure_iff] at hmem
  obtain ⟨n, γ, w, hγ, hsum⟩ := add_closure_form C _ hmem
  obtain ⟨x, y, hxy⟩ := weighted_decompose γ w hsum
  refine hC ?_
  rw [hxy]
  refine Subsemiring.sum_mem _ (fun i _ => C.mul_mem (hγ i) (C.add_mem ?_ (C.mul_mem ha ?_)))
  · rw [pow_two]; exact hCsq (x i)
  · rw [pow_two]; exact hCsq (y i)

/-! ### Order-compatible real closure: the maximization

Given an *ordered* field `F` (positive cone `P_F = nonneg F`), we maximize
the intermediate fields `S` of an algebraically closed `C ⊇ F` for which
`P_F` still generates a *proper* cone (`Compatible S`). The maximal such
`R` will be real closed with order extending `≤_F`. -/

section OrderCompatible

variable {F : Type*} [Field F] [LinearOrder F] [IsStrictOrderedRing F]
variable {C : Type*} [Field C] [Algebra F C]

/-- The cone generated in `S` by `F`'s positive cone together with all
squares of `S`. -/
def genCone (S : IntermediateField F C) : Subsemiring ↥S :=
  Subsemiring.closure (((Subsemiring.nonneg F).map (algebraMap F ↥S) : Set ↥S) ∪ {x | IsSquare x})

/-- `S` is *compatible* (with `F`'s order) if `genCone S` is proper. -/
def Compatible (S : IntermediateField F C) : Prop := (-1 : ↥S) ∉ genCone S

omit [LinearOrder F] [IsStrictOrderedRing F] in
/-- A finite family in a chain of intermediate fields lies in one member. -/
private theorem exists_mem_chain {c : Set (IntermediateField F C)} (hc : IsChain (· ≤ ·) c)
    (hne : c.Nonempty) {n : ℕ} (v : Fin n → C) (hv : ∀ i, v i ∈ sSup c) :
    ∃ S ∈ c, ∀ i, v i ∈ S := by
  have hdir : DirectedOn (· ≤ ·) c := hc.directedOn
  induction n with
  | zero => obtain ⟨S, hS⟩ := hne; exact ⟨S, hS, fun i => i.elim0⟩
  | succ n ih =>
    obtain ⟨S, hS, hSv⟩ := ih (fun i => v i.succ) (fun i => hv i.succ)
    have hmem : ∃ S' ∈ c, v 0 ∈ S' := by
      have hx' : v 0 ∈ (sSup c).toSubfield := hv 0
      rw [IntermediateField.sSup_toSubfield c hne] at hx'
      have hne' : (IntermediateField.toSubfield '' c).Nonempty := hne.image _
      have hdir' : DirectedOn (· ≤ ·) (IntermediateField.toSubfield '' c) := by
        rintro _ ⟨Sa, hSa, rfl⟩ _ ⟨Sb, hSb, rfl⟩
        obtain ⟨Sc, hSc, haSc, hbSc⟩ := hdir Sa hSa Sb hSb
        exact ⟨Sc.toSubfield, ⟨Sc, hSc, rfl⟩, haSc, hbSc⟩
      obtain ⟨s, ⟨S', hS', rfl⟩, hxs⟩ := (Subfield.mem_sSup_of_directedOn hne' hdir').mp hx'
      exact ⟨S', hS', hxs⟩
    obtain ⟨S', hS', hv0⟩ := hmem
    obtain ⟨T, hT, hST, hS'T⟩ := hdir S hS S' hS'
    exact ⟨T, hT, fun i => Fin.cases (hS'T hv0) (fun j => hST (hSv j)) i⟩

private theorem mem_genCone_of_repr (S : IntermediateField F C) {n : ℕ} (p : Fin n → F)
    (hp : ∀ i, p i ∈ Subsemiring.nonneg F) (z : Fin n → ↥S)
    (h : (-1 : ↥S) = ∑ i, algebraMap F ↥S (p i) * (z i) ^ 2) : ¬ Compatible S := by
  refine fun hcomp => hcomp ?_
  rw [genCone, h]
  refine Subsemiring.sum_mem _ (fun i _ => Subsemiring.mul_mem _
    (Subsemiring.subset_closure (Or.inl ⟨p i, hp i, rfl⟩))
    (Subsemiring.subset_closure (Or.inr ⟨z i, pow_two (z i)⟩)))

/-- The supremum of a chain of compatible fields is compatible. -/
private theorem sSup_compatible_of_chain {c : Set (IntermediateField F C)}
    (hc : IsChain (· ≤ ·) c) (hne : c.Nonempty) (hcomp : ∀ S ∈ c, Compatible S) :
    Compatible (sSup c) := by
  intro hmem
  rw [genCone, Subsemiring.mem_closure_iff] at hmem
  obtain ⟨n, p, z, hp, hsum⟩ := add_closure_form (Subsemiring.nonneg F) _ hmem
  obtain ⟨S, hS, hSz⟩ := exists_mem_chain hc hne (fun i => (z i).val) (fun i => (z i).2)
  set z' : Fin n → ↥S := fun i => ⟨(z i).val, hSz i⟩
  have heq : (-1 : ↥S) = ∑ i, algebraMap F ↥S (p i) * (z' i) ^ 2 := by
    apply (IntermediateField.inclusion (le_sSup hS)).injective
    rw [map_neg, map_one, map_sum]
    simp only [map_mul, map_pow]
    exact hsum
  exact mem_genCone_of_repr S p hp z' heq (hcomp S hS)

/-- `⊥ ≅ F` is compatible. -/
private theorem bot_compatible : Compatible (⊥ : IntermediateField F C) := by
  intro hmem
  rw [genCone, Subsemiring.mem_closure_iff] at hmem
  obtain ⟨n, p, z, hp, hsum⟩ := add_closure_form (Subsemiring.nonneg F) _ hmem
  have key : (-1 : F) = ∑ i, p i * (IntermediateField.botEquiv F C (z i)) ^ 2 := by
    have hb := congrArg (IntermediateField.botEquiv F C) hsum
    rw [map_neg, map_one, map_sum] at hb
    rw [hb]
    exact Finset.sum_congr rfl (fun i _ => by rw [map_mul, map_pow, AlgEquiv.commutes]; simp)
  have hnn : (0 : F) ≤ ∑ i, p i * (IntermediateField.botEquiv F C (z i)) ^ 2 :=
    Finset.sum_nonneg (fun i _ => mul_nonneg (hp i) (sq_nonneg _))
  rw [← key] at hnn
  exact absurd hnn (by norm_num)

/-- There is a maximal compatible intermediate field of `C` over `F`. -/
theorem exists_maximal_compatible :
    ∃ R : IntermediateField F C,
      Compatible R ∧ ∀ S : IntermediateField F C, Compatible S → R ≤ S → S = R := by
  obtain ⟨R, hR, hmax⟩ := zorn_le₀ {S : IntermediateField F C | Compatible S}
    (fun cc hsub hchain => by
      rcases cc.eq_empty_or_nonempty with rfl | hne
      · exact ⟨⊥, bot_compatible, fun _ h => h.elim⟩
      · exact ⟨sSup cc, sSup_compatible_of_chain hchain hne (fun S hS => hsub hS),
          fun S hS => le_sSup hS⟩)
  exact ⟨R, hR, fun S hS hle => le_antisymm (hmax hS hle) hle⟩

/-- The cone generated by `F`'s positive cone and squares in an `F`-algebra
`A` (the `F₁`-side analogue of `genCone`, used for the lift argument). -/
def genConeAlg (A : Type*) [CommRing A] [Algebra F A] : Subsemiring A :=
  Subsemiring.closure (((Subsemiring.nonneg F).map (algebraMap F A) : Set A) ∪ {x | IsSquare x})

/-- Transfer: every `genCone S` element of `S = f.fieldRange` pulls back
along `f` to a `genConeAlg F₁` element. -/
private theorem transfer {R : IntermediateField F C} (F₁ : Type*) [Field F₁]
    [Algebra (↥R) F₁] [Algebra F F₁] [IsScalarTower F (↥R) F₁] (f : F₁ →ₐ[↥R] C)
    (S : IntermediateField F C) (hSrange : (S : Set C) = Set.range f)
    (s : ↥S) (hs : s ∈ genCone S) :
    ∃ t : F₁, f t = s.val ∧ t ∈ genConeAlg (F := F) F₁ := by
  induction hs using Subsemiring.closure_induction with
  | mem x hx =>
    rcases hx with ⟨p, hp, rfl⟩ | ⟨w, rfl⟩
    · refine ⟨algebraMap F F₁ p, ?_, Subsemiring.subset_closure (Or.inl ⟨p, hp, rfl⟩)⟩
      rw [IsScalarTower.algebraMap_apply F ↥R F₁, f.commutes,
        ← IsScalarTower.algebraMap_apply F ↥R C, ← IntermediateField.coe_algebraMap_apply]
    · obtain ⟨u, hu⟩ : ∃ u : F₁, f u = w.val := by
        have hw : (w : C) ∈ (S : Set C) := w.2
        rw [hSrange] at hw; exact hw
      exact ⟨u ^ 2, by rw [map_pow, hu]; push_cast; ring,
        Subsemiring.subset_closure (Or.inr ⟨u, pow_two u⟩)⟩
  | zero => exact ⟨0, by simp, Subsemiring.zero_mem _⟩
  | one => exact ⟨1, by simp, Subsemiring.one_mem _⟩
  | add x y _ _ ihx ihy =>
    obtain ⟨tx, htx, hmx⟩ := ihx; obtain ⟨ty, hty, hmy⟩ := ihy
    exact ⟨tx + ty, by rw [map_add, htx, hty]; rfl, Subsemiring.add_mem _ hmx hmy⟩
  | mul x y _ _ ihx ihy =>
    obtain ⟨tx, htx, hmx⟩ := ihx; obtain ⟨ty, hty, hmy⟩ := ihy
    exact ⟨tx * ty, by rw [map_mul, htx, hty]; rfl, Subsemiring.mul_mem _ hmx hmy⟩

variable [IsAlgClosed C]

/-- **No nontrivial compatible algebraic extension.** A compatible
algebraic extension `F₁` of a maximal compatible field `R` is trivial
(`algebraMap` surjective). Proof by lifting `F₁ ↪ C` and using maximality
(adapts Theorem 2.31's argument to the compatible setting). -/
theorem maximal_no_compatible_ext (R : IntermediateField F C)
    (hmax : ∀ S : IntermediateField F C, Compatible S → R ≤ S → S = R)
    (F₁ : Type*) [Field F₁] [Algebra (↥R) F₁] [Algebra F F₁] [IsScalarTower F (↥R) F₁]
    (halg : Algebra.IsAlgebraic (↥R) F₁) (hcompat : (-1 : F₁) ∉ genConeAlg (F := F) F₁) :
    Function.Surjective (algebraMap (↥R) F₁) := by
  intro y
  let f : F₁ →ₐ[↥R] C := IsAlgClosed.lift
  let S : IntermediateField F C := f.fieldRange.restrictScalars F
  have hSrange : (S : Set C) = Set.range f := by
    simp [S, IntermediateField.coe_restrictScalars, AlgHom.coe_fieldRange]
  have hRS : R ≤ S := fun z hz =>
    AlgHom.mem_fieldRange.mpr ⟨algebraMap (↥R) F₁ ⟨z, hz⟩, f.commutes ⟨z, hz⟩⟩
  have hS_compat : Compatible S := by
    intro hmem
    obtain ⟨t, ht, hmt⟩ := transfer F₁ f S hSrange (-1) hmem
    have htneg : t = -1 := f.injective (by simpa using ht)
    exact hcompat (htneg ▸ hmt)
  have hfy_mem : (f y : C) ∈ R := by
    have hmem : (f y : C) ∈ S := AlgHom.mem_fieldRange.mpr ⟨y, rfl⟩
    rw [hmax S hS_compat hRS] at hmem; exact hmem
  exact ⟨⟨f y, hfy_mem⟩, f.injective (by simp [f.commutes])⟩

open Azurite.BPR.Theorem2_11 in
/-- **Square property.** For maximal compatible `R` with a total cone `T`
(from `prop_2_8`), every `a ∈ T` is a square: otherwise `R(√a)` would be a
nontrivial compatible algebraic extension (`adjoin_compatible` +
`maximal_no_compatible_ext`). -/
theorem square_property (R : IntermediateField F C)
    (hmax : ∀ S : IntermediateField F C, Compatible S → R ≤ S → S = R)
    (T : RingCone ↥R) (hTsub : (genCone R : Set ↥R) ⊆ T) {a : ↥R} (ha : a ∈ T) :
    IsSquare a := by
  by_contra ha_sq
  haveI : Fact (Irreducible (sqSubC a)) := ⟨irred_X_sq_sub_C ha_sq⟩
  have halg := adjoinRoot_isAlgebraic (R := ↥R) (monic_sq_sub_C a)
  have hTsq : ∀ x : ↥R, x * x ∈ T.toSubsemiring :=
    fun x => hTsub (Subsemiring.subset_closure (Or.inr ⟨x, rfl⟩))
  have hTneg : (-1 : ↥R) ∉ T.toSubsemiring := fun h =>
    one_ne_zero (T.eq_zero_of_mem_of_neg_mem' T.one_mem h)
  have hadj := adjoin_compatible T.toSubsemiring hTsq ha hTneg ha_sq
  have hcompat : (-1 : AdjoinRoot (sqSubC a)) ∉ genConeAlg (F := F) (AdjoinRoot (sqSubC a)) := by
    intro hmem
    refine hadj (Subsemiring.closure_mono ?_ hmem)
    rintro x (⟨p, hp, rfl⟩ | hsq)
    · refine Or.inl ⟨algebraMap F ↥R p,
        hTsub (Subsemiring.subset_closure (Or.inl ⟨p, hp, rfl⟩)), ?_⟩
      rw [IsScalarTower.algebraMap_apply F ↥R (AdjoinRoot (sqSubC a))]
    · exact Or.inr hsq
  obtain ⟨r, hr⟩ := maximal_no_compatible_ext R hmax (AdjoinRoot (sqSubC a)) halg hcompat
    (AdjoinRoot.root (sqSubC a))
  refine ha_sq ⟨r, ?_⟩
  have hkey : algebraMap (↥R) (AdjoinRoot (sqSubC a)) (r * r) = algebraMap _ _ a := by
    rw [map_mul, hr, ← pow_two, root_sq_sub_C]
  exact (FaithfulSMul.algebraMap_injective (↥R) (AdjoinRoot (sqSubC a)) hkey).symm

/-- Squares lie in any total cone. -/
private theorem sq_mem_total {A : Type*} [CommRing A] (Q : RingCone A)
    (hQ : HasMemOrNegMem Q) (x : A) : x * x ∈ Q := by
  rcases hQ.mem_or_neg_mem x with h | h
  · exact mul_mem h h
  · have := mul_mem h h; simpa using this

omit [IsAlgClosed C] in
/-- A compatible intermediate field is formally real: `-1` is not a sum of squares,
since the sums of squares sit inside `genCone R`, which omits `-1`. -/
private theorem compatible_isRealField (R : IntermediateField F C) (hcomp : Compatible R) :
    IsRealField ↥R := by
  rw [isRealField_iff]
  intro hmem
  refine hcomp ?_
  have hsum : ∀ s : ↥R, IsSumSq s → s ∈ genCone R := by
    intro s hs
    induction hs with
    | zero => exact zero_mem _
    | sq_add a _ ih => exact add_mem (Subsemiring.subset_closure (Or.inr ⟨a, rfl⟩)) ih
  exact hsum _ hmem

open Azurite.BPR.Theorem2_11 in
/-- **Order-compatible real closure (existence).** Inside any algebraically closed
extension `C` of an ordered field `F`, there is an intermediate field `R`, algebraic
over `F`, that is real closed and whose order extends that of `F` (every `p ≥ 0` in `F`
becomes a square in `R`).

Taking `R` maximal among the `P_F`-compatible intermediate fields, the square property
forces every nonnegative element of `F` to be a square in `R`, and the only real
algebraic extension of `R` is `R` itself (any real extension carries a total cone that
swallows `genConeAlg`, so it is compatible — hence trivial by maximality). Theorem 2.11
(d ⟹ a) then upgrades "no nontrivial real algebraic extension" to "real closed". -/
theorem exists_orderCompatible_realClosure :
    ∃ R : IntermediateField F C, IsRealClosed ↥R ∧
      ∀ p : F, 0 ≤ p → IsSquare (algebraMap F ↥R p) := by
  obtain ⟨R, hcomp, hmax⟩ := exists_maximal_compatible (F := F) (C := C)
  obtain ⟨T, hTsub, hTtotal⟩ := prop_2_8 (F := ↥R)
    ⟨fun x => Subsemiring.subset_closure (Or.inr ⟨x, by rw [pow_two]⟩), hcomp⟩
  have hreal : IsRealField ↥R := compatible_isRealField R hcomp
  have hnoext : HasNoNontrivialRealAlgebraicExtension ↥R := by
    refine ⟨hreal, fun F₁ _ _ halg hreal₁ => ?_⟩
    letI : Algebra F F₁ := ((algebraMap (↥R) F₁).comp (algebraMap F ↥R)).toAlgebra
    haveI : IsScalarTower F (↥R) F₁ := IsScalarTower.of_algebraMap_eq fun _ => rfl
    obtain ⟨Q, hQ⟩ := theorem_2_7_b_of_c (theorem_2_7_a_of_b hreal₁)
    have hcompatF1 : (-1 : F₁) ∉ genConeAlg (F := F) F₁ := by
      intro hmem
      have hsub : genConeAlg (F := F) F₁ ≤ Q.toSubsemiring := by
        apply Subsemiring.closure_le.2
        rintro x (⟨p, hp, rfl⟩ | ⟨y, rfl⟩)
        · have hpT := hTsub (Subsemiring.subset_closure (Or.inl ⟨p, hp, rfl⟩))
          obtain ⟨s, hs⟩ := square_property R hmax T hTsub hpT
          rw [IsScalarTower.algebraMap_apply F ↥R F₁, hs, map_mul]
          exact sq_mem_total Q hQ _
        · exact sq_mem_total Q hQ y
      exact one_ne_zero (Q.eq_zero_of_mem_of_neg_mem' Q.one_mem (hsub hmem))
    exact maximal_no_compatible_ext R hmax F₁ halg hcompatF1
  refine ⟨R, theorem_2_11_d_a hnoext, fun p hp => ?_⟩
  exact square_property R hmax T hTsub
    (hTsub (Subsemiring.subset_closure (Or.inl ⟨p, (Subsemiring.mem_nonneg).2 hp, rfl⟩)))

end OrderCompatible

variable (C : Type*) [Field C] (F : Type*) [Field F] [IsSemireal F] [Algebra F C]

/-- `⊥` is semireal: it is isomorphic to the formally real base `F`. -/
private lemma bot_isSemireal : IsSemireal ↥(⊥ : IntermediateField F C) := by
  apply IsSemireal.of_not_isSumSq_neg_one
  intro h
  have h' := isSumSq_map (IntermediateField.botEquiv F C).toAlgHom.toRingHom h
  simp at h'
  exact IsSemireal.not_isSumSq_neg_one F h'

omit [IsSemireal F] in
/-- The supremum of a chain of semireal intermediate fields is semireal. -/
private lemma sSup_isSemireal_of_chain
    {c : Set (IntermediateField F C)} (hc : IsChain (· ≤ ·) c)
    (hne : c.Nonempty) (hsemi : ∀ S ∈ c, IsSemireal ↥S) :
    IsSemireal ↥(sSup c) := by
  apply IsSemireal.of_not_isSumSq_neg_one
  intro h
  have hdir : DirectedOn (· ≤ ·) c := hc.directedOn
  have hmem : ∀ (x : C), x ∈ (sSup c : IntermediateField F C) → ∃ S ∈ c, x ∈ S := by
    intro x hx
    have hx' : x ∈ (sSup c).toSubfield := hx
    rw [IntermediateField.sSup_toSubfield c hne] at hx'
    have hne' : (IntermediateField.toSubfield '' c).Nonempty := hne.image _
    have hdir' : DirectedOn (· ≤ ·) (IntermediateField.toSubfield '' c) := by
      rintro _ ⟨Sa, hSa, rfl⟩ _ ⟨Sb, hSb, rfl⟩
      obtain ⟨Sc, hSc, haSc, hbSc⟩ := hdir Sa hSa Sb hSb
      exact ⟨Sc.toSubfield, ⟨Sc, hSc, rfl⟩, haSc, hbSc⟩
    obtain ⟨s, ⟨S, hS, rfl⟩, hxs⟩ := (Subfield.mem_sSup_of_directedOn hne' hdir').mp hx'
    exact ⟨S, hS, hxs⟩
  suffices ∀ (x : ↥(sSup c)), IsSumSq x →
      ∃ S ∈ c, ∃ y : ↥S, (y : C) = (x : C) ∧ IsSumSq y by
    obtain ⟨S, hS, y, hy, hsy⟩ := this _ h
    have : y = -1 := Subtype.val_injective (by simp [hy])
    exact absurd (by rwa [this] at hsy) (hsemi S hS).not_isSumSq_neg_one
  intro x hx
  induction hx with
  | zero =>
    obtain ⟨S, hS⟩ := hne
    exact ⟨S, hS, 0, by simp, .zero⟩
  | sq_add a _ ih =>
    obtain ⟨S₁, hS₁, y₁, hy₁, hsy₁⟩ := ih
    obtain ⟨S₂, hS₂, ha_S₂⟩ := hmem a.val a.2
    obtain ⟨S₃, hS₃, h₁₃, h₂₃⟩ := hdir S₁ hS₁ S₂ hS₂
    refine ⟨S₃, hS₃,
      ⟨a.val, h₂₃ ha_S₂⟩ * ⟨a.val, h₂₃ ha_S₂⟩ + IntermediateField.inclusion h₁₃ y₁, ?_, ?_⟩
    · simp [IntermediateField.coe_inclusion, hy₁]
    · exact .sq_add _ (isSumSq_map (IntermediateField.inclusion h₁₃).toRingHom hsy₁)


/-- There exists a maximal semireal intermediate field of `C` over `F`. -/
private lemma exists_maximal_semireal :
    ∃ R : IntermediateField F C,
      IsSemireal ↥R ∧ ∀ S : IntermediateField F C, IsSemireal ↥S → R ≤ S → S = R := by
  have ⟨R, ⟨hR_semi, hR_max⟩⟩ := zorn_le₀
    {S : IntermediateField F C | IsSemireal ↥S}
    (fun cc hc_sub hc_chain => by
      rcases cc.eq_empty_or_nonempty with rfl | hne
      · exact ⟨⊥, bot_isSemireal C F, fun _ h => h.elim⟩
      · exact ⟨sSup cc, sSup_isSemireal_of_chain C F hc_chain hne (fun S hS => hc_sub hS),
          fun S hS => le_sSup hS⟩)
  exact ⟨R, hR_semi, fun S hS hle => le_antisymm (hR_max hS hle) hle⟩

variable [IsAlgClosed C]

omit [IsSemireal F] in
/-- The maximal semireal intermediate field has no nontrivial real algebraic
extension. -/
private lemma maximal_hasNoNontrivialRealAlgebraicExtension
    (R : IntermediateField F C) (hR : IsSemireal ↥R)
    (hmax : ∀ S : IntermediateField F C, IsSemireal ↥S → R ≤ S → S = R) :
    Azurite.BPR.HasNoNontrivialRealAlgebraicExtension ↥R := by
  constructor
  · exact hR
  · intro F₁ _ _ halg hreal x
    letI : Algebra F F₁ := (algebraMap ↥R F₁).comp (algebraMap F ↥R) |>.toAlgebra
    haveI : IsScalarTower F ↥R F₁ := IsScalarTower.of_algebraMap_eq fun _ => rfl
    let f : F₁ →ₐ[↥R] C := IsAlgClosed.lift
    let S : IntermediateField F C := f.fieldRange.restrictScalars F
    have hRS : R ≤ S := by
      intro y hy
      show y ∈ f.fieldRange
      exact AlgHom.mem_fieldRange.mpr ⟨algebraMap ↥R F₁ ⟨y, hy⟩, f.commutes ⟨y, hy⟩⟩
    have hS_semi : IsSemireal ↥S := by
      apply IsSemireal.of_not_isSumSq_neg_one
      intro h
      suffices ∀ (s : ↥S), IsSumSq s → ∃ t : F₁, f t = s.val ∧ IsSumSq t by
        obtain ⟨t, ht, hst⟩ := this _ h
        have : t = -1 := f.injective (by simp [ht])
        exact absurd (by rwa [this] at hst) hreal.not_isSumSq_neg_one
      intro s hs
      induction hs with
      | zero => exact ⟨0, by simp, .zero⟩
      | sq_add a _ ih =>
        obtain ⟨t₁, ht₁, hst₁⟩ := ih
        have ha_mem : a.val ∈ f.fieldRange := a.2
        obtain ⟨b, hb⟩ := AlgHom.mem_fieldRange.mp ha_mem
        exact ⟨b * b + t₁, by simp [map_add, map_mul, hb, ht₁], .sq_add b hst₁⟩
    have hSR := hmax S hS_semi hRS
    have hfx_mem : (f x : C) ∈ R := by
      have : (f x : C) ∈ S := AlgHom.mem_fieldRange.mpr ⟨x, rfl⟩
      convert this using 1
      exact hSR.symm
    exact ⟨⟨f x, hfx_mem⟩, f.injective (by simp [f.commutes])⟩

/-- **Real closure inside an algebraically closed field (generalized
Theorem 2.31).** For a formally real base `F` and an algebraically closed
field `C ⊇ F` of characteristic zero, there is a real closed intermediate
field `F ⊆ R ⊆ C`. -/
theorem exists_isRealClosed_intermediateField :
    ∃ R : IntermediateField F C, IsRealClosed ↥R := by
  obtain ⟨R, hR, hmax⟩ := exists_maximal_semireal C F
  exact ⟨R, Azurite.BPR.Theorem2_11.theorem_2_11_d_a
    (maximal_hasNoNontrivialRealAlgebraicExtension C F R hR hmax)⟩

/-- **Existence of a real closure.** Every formally real field `F` has a
real closed algebraic extension: a real closed intermediate field of
`AlgebraicClosure F` containing `F`. (Its elements are algebraic over `F`
since `AlgebraicClosure F` is.) -/
theorem exists_isRealClosed_algebraic (F : Type*) [Field F] [IsSemireal F] :
    ∃ R : IntermediateField F (AlgebraicClosure F), IsRealClosed ↥R :=
  exists_isRealClosed_intermediateField (AlgebraicClosure F) F

/-- **Real closure of an ordered field.** Every ordered field `F` has a real
closed algebraic extension whose order extends that of `F`: a real closed
intermediate field `R` of `AlgebraicClosure F` in which every nonnegative
element of `F` becomes a square (i.e. nonnegative for `R`'s unique order). -/
theorem exists_orderCompatible_realClosure_algebraic
    (F : Type*) [Field F] [LinearOrder F] [IsStrictOrderedRing F] :
    ∃ R : IntermediateField F (AlgebraicClosure F), IsRealClosed ↥R ∧
      ∀ p : F, 0 ≤ p → IsSquare (algebraMap F ↥R p) :=
  exists_orderCompatible_realClosure (C := AlgebraicClosure F)

end Azurite.BPR.RealClosure
