/-
Copyright © 2026 Mikhail Hogrefe

This file is part of Azurite.

Azurite is free software: you can redistribute it and/or modify it under the terms of the Apache
License, Version 2.0. See <https://www.apache.org/licenses/LICENSE-2.0>.
-/

import Azurite.BasuPollackRoy.Chapter4.Section4_4.FiniteMapping
import Azurite.BasuPollackRoy.Chapter4.Section4_4.IdealOfPolynomials

/-!
# BPR §4.5: zero-dimensional systems

Let `𝒫` be a finite subset of `K[X₁, …, X_k]`. The set of zeros of `𝒫` in `Cᵏ` (`C` an
algebraically closed field extension of `K`),
`Zer(𝒫, Cᵏ) = {x ∈ Cᵏ | ⋀_{P ∈ 𝒫} P(x) = 0}` (`zerOfFinset`, recalled from §4.4), is also
called the set of solutions in `Cᵏ` of the polynomial system of equations `𝒫 = 0`. Abusing
terminology, we speak of the solutions of a polynomial system `𝒫`.

A system of polynomial equations `𝒫` is *zero-dimensional* if it has a finite number of
solutions in `Cᵏ`, i.e. if `Zer(𝒫, Cᵏ)` is a non-empty finite set (`IsZeroDimensional`).

We denote by `Ideal(𝒫, K)` the ideal generated by `𝒫` in `K[X₁, …, X_k]` (`idealOfPolys`,
recalled from §4.4).
-/

namespace Azurite.BPR.Chapter4

open MvPolynomial

variable {k : ℕ} {K : Type*} [Field K]

/-- **BPR Definition (zero-dimensional system).** A system of polynomial equations
`𝒫 ⊆ K[X₁, …, X_k]` is *zero-dimensional* (over an algebraically closed field extension `C` of
`K`) if its set of solutions `Zer(𝒫, Cᵏ)` is a non-empty finite set. -/
def IsZeroDimensional (C : Type*) [Field C] [Algebra K C]
    (Ps : Finset (MvPolynomial (Fin k) K)) : Prop :=
  (zerOfFinset C Ps).Nonempty ∧ (zerOfFinset C Ps).Finite

theorem isZeroDimensional_iff {C : Type*} [Field C] [Algebra K C]
    {Ps : Finset (MvPolynomial (Fin k) K)} :
    IsZeroDimensional C Ps ↔ (zerOfFinset C Ps).Nonempty ∧ (zerOfFinset C Ps).Finite :=
  Iff.rfl

end Azurite.BPR.Chapter4
