import Azurite.BasuPollackRoy.Chapter4.Section4_4.IdealOfPolynomials
import Azurite.BasuPollackRoy.Chapter4.Section4_4.FiniteMapping
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.MvPolynomial.Tower
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Finsupp.Defs

/-!
# BPR §4.5: the algebras `A` and `Ā`, and Lemma 4.87 (`A ⊂ Ā`)

Let `K` be a field, `C` an algebraically closed field containing `K`, and `𝒫` a finite subset
of `K[X₁, …, X_k]`. Set
* `A = K[X₁, …, X_k] / Ideal(𝒫, K)` (`quotPolys`), and
* `Ā = C[X₁, …, X_k] / Ideal(𝒫, C)` (`quotPolysExt`),
where `Ideal(𝒫, C)` is the ideal generated by `𝒫` in `C[X₁, …, X_k]` (`idealOfPolysExt`).

Given `x ∈ Zer(𝒫, Cᵏ)` and `Q ∈ Ā`, the value `Q(x) ∈ C` is well defined, since two polynomials
of `C[X₁, …, X_k]` with the same image in `Ā` have the same value at `x` (`evalBar`).

**Lemma 4.87 (`lemma_4_87`).** `A ⊂ Ā`: the natural morphism `A → Ā` (`inclExt`) is injective.

The proof is the elementary linear-algebra descent of BPR: if `a, b ∈ K[X]` are equal modulo
`Ideal(𝒫, C)`, then `a - b = ∑_{P} A_P P` with `A_P ∈ C[X]`. Viewing the unknown coefficients of
the `A_P` as the solution of a linear system with coefficients in `K`, solvability over `C`
forces solvability over `K`, so `a - b = ∑_P C_P P` with `C_P ∈ K[X]`. We realize this descent
concretely by a `K`-linear retraction `π : C → K` of `K ↪ C` (which exists since `K ↪ C` is an
injective map of `K`-vector spaces), extended coefficient-wise to `prj : C[X] → K[X]`. This `prj`
satisfies `prj(map P) = P` and the projection formula `prj(map P · h) = P · prj h` for `P ∈ K[X]`,
which together turn any `C`-combination `map a = ∑_P B_P · map P` into the `K`-combination
`a = ∑_P P · prj(B_P)`.
-/

namespace Azurite.BPR.Chapter4

open MvPolynomial
open scoped Classical

variable {k : ℕ} {K : Type*} [Field K] (C : Type*) [Field C] [Algebra K C]

/-- `A = K[X₁, …, X_k] / Ideal(𝒫, K)`. -/
abbrev quotPolys (Ps : Finset (MvPolynomial (Fin k) K)) : Type _ :=
  MvPolynomial (Fin k) K ⧸ idealOfPolys Ps

/-- `Ideal(𝒫, C)`: the ideal generated by `𝒫` in `C[X₁, …, X_k]` (the images of the members of
`𝒫` under the coefficient inclusion `K ↪ C`). -/
noncomputable def idealOfPolysExt (Ps : Finset (MvPolynomial (Fin k) K)) :
    Ideal (MvPolynomial (Fin k) C) :=
  idealOfPolys (Ps.image (MvPolynomial.map (algebraMap K C)))

/-- `Ā = C[X₁, …, X_k] / Ideal(𝒫, C)`. -/
abbrev quotPolysExt (Ps : Finset (MvPolynomial (Fin k) K)) : Type _ :=
  MvPolynomial (Fin k) C ⧸ idealOfPolysExt C Ps

/-- `Ideal(𝒫, C)` is the extension `Ideal.map` of `Ideal(𝒫, K)` along `K[X] → C[X]`. -/
theorem idealOfPolysExt_eq_map (Ps : Finset (MvPolynomial (Fin k) K)) :
    idealOfPolysExt C Ps
      = Ideal.map (MvPolynomial.map (algebraMap K C)) (idealOfPolys Ps) := by
  rw [idealOfPolysExt, idealOfPolys, idealOfPolys, Ideal.map_span, Finset.coe_image]

/-- **The descent (core of Lemma 4.87).** If the image of `a ∈ K[X]` lands in `Ideal(𝒫, C)`,
then `a` already lies in `Ideal(𝒫, K)`. -/
theorem mem_idealOfPolys_of_map_mem {Ps : Finset (MvPolynomial (Fin k) K)}
    {a : MvPolynomial (Fin k) K}
    (h : MvPolynomial.map (algebraMap K C) a ∈ idealOfPolysExt C Ps) :
    a ∈ idealOfPolys Ps := by
  classical
  -- A `K`-linear retraction `π : C → K` of `K ↪ C`.
  obtain ⟨π, hπ⟩ := LinearMap.exists_leftInverse_of_injective
    (Algebra.linearMap K C) (LinearMap.ker_eq_bot.2 (algebraMap K C).injective)
  have hπa : ∀ x : K, π (algebraMap K C x) = x := fun x => by
    simpa [Algebra.linearMap_apply] using LinearMap.congr_fun hπ x
  -- Extend `π` coefficient-wise to `prj : C[X] → K[X]`.
  -- (`AddMonoidAlgebra` is now a structure, so the coefficient-wise
  -- extension goes through `coeffLinearEquiv` rather than raw `Finsupp`.)
  let prj : MvPolynomial (Fin k) C →ₗ[K] MvPolynomial (Fin k) K :=
    (AddMonoidAlgebra.coeffLinearEquiv (R := K)).symm.toLinearMap ∘ₗ
      Finsupp.mapRange.linearMap π ∘ₗ
      (AddMonoidAlgebra.coeffLinearEquiv (R := K)).toLinearMap
  have prjcoeff : ∀ (p : MvPolynomial (Fin k) C) (m : Fin k →₀ ℕ),
      (prj p).coeff m = π (p.coeff m) := fun p m => by
    show ((AddMonoidAlgebra.coeffLinearEquiv (R := K)).symm
      (Finsupp.mapRange π (map_zero π)
        ((AddMonoidAlgebra.coeffLinearEquiv (R := K)) p))).coeff m = π (p.coeff m)
    simp [AddMonoidAlgebra.coeffLinearEquiv_apply, AddMonoidAlgebra.coeffLinearEquiv_symm_apply]
  -- `prj` is a retraction of base change: `prj(map g) = g`.
  have prjmap : ∀ g : MvPolynomial (Fin k) K,
      prj (MvPolynomial.map (algebraMap K C) g) = g := fun g => by
    refine MvPolynomial.ext _ _ fun m => ?_
    rw [prjcoeff, MvPolynomial.coeff_map, hπa]
  -- Projection formula: `prj(map P · q) = P · prj q`.
  have prjmul : ∀ (P : MvPolynomial (Fin k) K) (q : MvPolynomial (Fin k) C),
      prj (MvPolynomial.map (algebraMap K C) P * q) = P * prj q := fun P q => by
    refine MvPolynomial.ext _ _ fun m => ?_
    rw [prjcoeff, MvPolynomial.coeff_mul, map_sum, MvPolynomial.coeff_mul]
    refine Finset.sum_congr rfl fun x _ => ?_
    rw [MvPolynomial.coeff_map, ← Algebra.smul_def, map_smul, smul_eq_mul, ← prjcoeff]
  -- Extract a `C`-combination of `map a` over `𝒫`, then apply `prj`.
  have h' : MvPolynomial.map (algebraMap K C) a
      ∈ idealOfPolys (Ps.image (MvPolynomial.map (algebraMap K C))) := h
  obtain ⟨B, hB⟩ := (mem_idealOfPolys_iff _ _).mp h'
  have ha : a = ∑ q ∈ Ps.image (MvPolynomial.map (algebraMap K C)), prj (B q * q) := by
    rw [← prjmap a, ← hB, map_sum]
  rw [ha]
  refine Submodule.sum_mem _ fun q hq => ?_
  obtain ⟨P, hP, rfl⟩ := Finset.mem_image.mp hq
  rw [mul_comm (B (MvPolynomial.map (algebraMap K C) P)) (MvPolynomial.map (algebraMap K C) P),
    prjmul]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span (Finset.mem_coe.mpr hP))

/-- **The natural morphism `A → Ā`** induced by the coefficient inclusion `K ↪ C`. -/
noncomputable def inclExt (Ps : Finset (MvPolynomial (Fin k) K)) :
    quotPolys Ps →+* quotPolysExt C Ps :=
  Ideal.quotientMap (idealOfPolysExt C Ps) (MvPolynomial.map (algebraMap K C))
    (by rw [idealOfPolysExt_eq_map]; exact Ideal.le_comap_map)

@[simp]
theorem inclExt_mk (Ps : Finset (MvPolynomial (Fin k) K)) (p : MvPolynomial (Fin k) K) :
    inclExt C Ps (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.map (algebraMap K C) p) :=
  Ideal.quotientMap_mk

/-- **Well-defined evaluation `Q ↦ Q(x)` on `Ā`.** For `x ∈ Zer(𝒫, Cᵏ)`, two polynomials of
`C[X₁, …, X_k]` with the same image in `Ā` have the same value at `x`, so evaluation descends to
a ring morphism `Ā → C`. -/
noncomputable def evalBar (Ps : Finset (MvPolynomial (Fin k) K)) (x : Fin k → C)
    (hx : x ∈ zerOfFinset C Ps) : quotPolysExt C Ps →+* C :=
  Ideal.Quotient.lift (idealOfPolysExt C Ps) (MvPolynomial.aeval x).toRingHom (by
    intro f hf
    have hf' : f ∈ idealOfPolys (Ps.image (MvPolynomial.map (algebraMap K C))) := hf
    refine aeval_eq_zero_of_mem_idealOfPolys hf' x fun q hq => ?_
    obtain ⟨P, hP, rfl⟩ := Finset.mem_image.mp hq
    rw [MvPolynomial.aeval_map_algebraMap]
    exact hx P hP)

@[simp]
theorem evalBar_mk (Ps : Finset (MvPolynomial (Fin k) K)) (x : Fin k → C)
    (hx : x ∈ zerOfFinset C Ps) (p : MvPolynomial (Fin k) C) :
    evalBar C Ps x hx (Ideal.Quotient.mk _ p) = MvPolynomial.aeval x p :=
  Ideal.Quotient.lift_mk _ _ _

/-- **BPR Lemma 4.87.** `A ⊂ Ā`: the natural morphism `A → Ā` is injective. -/
theorem lemma_4_87 (Ps : Finset (MvPolynomial (Fin k) K)) :
    Function.Injective (inclExt C Ps) := by
  unfold inclExt
  exact Ideal.quotientMap_injective' fun a ha => mem_idealOfPolys_of_map_mem C ha

end Azurite.BPR.Chapter4
