/-
  check_axioms.lean — Verify that every declaration in the Azurite
  namespace depends only on allowed axioms.

  Allowed axioms:
    * the standard three: `propext`, `Classical.choice`, `Quot.sound`;
    * `Lean.ofReduceBool` and `Lean.trustCompiler`, introduced by
      `native_decide`, which Azurite permits.

  Anything else — in particular `sorryAx` or a newly introduced user
  axiom — is an error: the offending declarations are listed and the
  script exits with a non-zero code, failing CI.

  Implementation notes: the dependency cone is walked with an explicit
  work list (no recursion, so no stack-depth limit, and immune to the
  reference cycles that mutually-recursive definitions produce in
  `getUsedConstantsAsSet`). Constants whose cone has been verified clean
  are recorded in a shared set, so later declarations skip already
  verified regions and the whole check is a single pass over the
  environment in the common (all-clean) case.

  Usage: lake env lean scripts/check_axioms.lean
-/
import Azurite

open Lean

/-- Axioms that Azurite declarations are allowed to depend on. -/
def allowedAxioms : List Name :=
  [`propext, `Classical.choice, `Quot.sound,
   `Lean.ofReduceBool, `Lean.trustCompiler]

/-- `native_decide` records each evaluated proposition as a generated
    auxiliary axiom named `<decl>._native.native_decide.ax_*` (depending on
    `Lean.ofReduceBool`), so the allowed set cannot be a fixed name list:
    every future `native_decide` use mints a fresh axiom. Recognize them by
    the consecutive `_native`/`native_decide` components Lean generates. -/
def isNativeDecideAux : Name → Bool
  | .str (.str (.str _ "_native") "native_decide") _ => true
  | .str p _ => isNativeDecideAux p
  | .num p _ => isNativeDecideAux p
  | .anonymous => false

/-- An axiom is allowed if it is in the fixed list or generated by
    `native_decide`. -/
def isAllowedAxiom (n : Name) : Bool :=
  allowedAxioms.contains n || isNativeDecideAux n

unsafe def checkAllAxioms : IO Unit := do
  let env ← importModules #[{ module := `Azurite }] {}
  -- Constants whose entire dependency cone is known to use only allowed
  -- axioms. Grows monotonically across the outer loop.
  let mut clean : Std.HashSet Name := {}
  let mut allAxioms : Std.HashSet Name := {}
  let mut violations : Array (Name × List Name) := #[]
  let mut count := 0
  for (root, _) in env.constants.map₁.toList do
    if root.getRoot == `Azurite && !root.isInternal then
      count := count + 1
      if clean.contains root then
        continue
      -- Iterative DFS over the dependency cone of `root`.
      let mut visited : Std.HashSet Name := {}
      let mut bad : Std.HashSet Name := {}
      let mut stack : Array Name := #[root]
      while true do
        let some n := stack.back? | break
        stack := stack.pop
        if visited.contains n || clean.contains n then
          continue
        visited := visited.insert n
        match env.constants.find? n with
        | some (.axiomInfo _) =>
            allAxioms := allAxioms.insert n
            if !isAllowedAxiom n then
              bad := bad.insert n
        | some ci =>
            for u in ci.getUsedConstantsAsSet do
              if !visited.contains u && !clean.contains u then
                stack := stack.push u
        | none => pure ()
      if bad.isEmpty then
        -- Everything reachable from `root` is verified clean; never
        -- traverse any of it again.
        for n in visited do
          clean := clean.insert n
      else
        violations := violations.push (root, bad.toList.mergeSort (·.toString < ·.toString))
  IO.println s!"Checked {count} declarations in Azurite.*"
  IO.println ""
  IO.println "Axioms used:"
  for ax in allAxioms.toList.mergeSort (·.toString < ·.toString) do
    let tag := if isAllowedAxiom ax then "" else "   ← NOT ALLOWED"
    IO.println s!"  {ax}{tag}"
  if violations.size > 0 then
    IO.println ""
    IO.println s!"✗ {violations.size} declaration(s) depend on disallowed axioms:"
    for (d, axs) in (violations.qsort (·.1.toString < ·.1.toString)) do
      IO.println s!"  {d}: {axs}"
    throw <| IO.userError "Axiom check failed."
  IO.println ""
  IO.println "✓ All declarations use only allowed axioms."

#eval checkAllAxioms
